In [1]:
%cd ../..

/home/dmoreno/ATAT_ZTF/elasticc_one

In [48]:
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np
import glob

In [49]:
dict_cols = {
    'oid': 'oid',
    'time': 'mjd',
    'flux': 'flux_diff_ujy',
    'flux_err': 'sigma_flux_diff_ujy',
    'detected': 'detected',
    'band': 'fid',
    'class': 'alerceclass'
}

In [50]:
# Astronomical objects and their labels
df_objid_label = pd.read_parquet('./data/datasets/ZTF_ff/processed/data_231206/objects.parquet')
df_objid_label = df_objid_label.reset_index()
df_objid_label = df_objid_label[[dict_cols['oid'], dict_cols['class']]]
df_objid_label.head()

            oid alerceclass
0  ZTF21acasmne     CV/Nova
1  ZTF19aaonuwr         LPV
2  ZTF17aabhkmn         YSO
3  ZTF18aatxhtl         QSO
4  ZTF18aaadfyl       RSCVn

In [51]:
path_chunks = sorted(glob.glob('./data/datasets/ZTF_ff/processed/data_231206/lightcurves_batch_*'))

df_lcs = []
for i, path_chunk in enumerate(path_chunks):
    print('Processing chunk {}'.format(i))
    df_chunk = pd.read_parquet('{}'.format(path_chunk))
    df_chunk = df_chunk[df_chunk[dict_cols['oid']].isin(df_objid_label[dict_cols['oid']].values)]
    df_chunk = df_chunk.groupby(dict_cols['oid']).apply(lambda x: x.sort_values(dict_cols['time'])).reset_index(drop=True)
    df_chunk_filtered = df_chunk[list(set(dict_cols.values()) - {dict_cols['class']})]
    df_lcs.append(df_chunk_filtered)

df_lcs = pd.concat(df_lcs)

Processing chunk 0
Processing chunk 1
Processing chunk 2
Processing chunk 3
Processing chunk 4
Processing chunk 5
Processing chunk 6
Processing chunk 7
Processing chunk 8
Processing chunk 9
Processing chunk 10
Processing chunk 11
Processing chunk 12
Processing chunk 13
Processing chunk 14
Processing chunk 15
Processing chunk 16
Processing chunk 17
Processing chunk 18
Processing chunk 19
Processing chunk 20
Processing chunk 21
Processing chunk 22
Processing chunk 23
Processing chunk 24
Processing chunk 25
Processing chunk 26
Processing chunk 27
Processing chunk 28
Processing chunk 29
Processing chunk 30
Processing chunk 31
Processing chunk 32
Processing chunk 33
Processing chunk 34
Processing chunk 35
Processing chunk 36
Processing chunk 37
Processing chunk 38
Processing chunk 39
Processing chunk 40
Processing chunk 41
Processing chunk 42
Processing chunk 43
Processing chunk 44
Processing chunk 45
Processing chunk 46
Processing chunk 47
Processing chunk 48
Processing chunk 49
Processing chunk 50
Processing chunk 51
Processing chunk 52
Processing chunk 53
Processing chunk 54
Processing chunk 55
Processing chunk 56
Processing chunk 57
Processing chunk 58
Processing chunk 59
Processing chunk 60
Processing chunk 61
Processing chunk 62
Processing chunk 63
Processing chunk 64
Processing chunk 65
Processing chunk 66
Processing chunk 67
Processing chunk 68
Processing chunk 69
Processing chunk 70
Processing chunk 71
Processing chunk 72
Processing chunk 73
Processing chunk 74
Processing chunk 75
Processing chunk 76
Processing chunk 77
Processing chunk 78
Processing chunk 79
Processing chunk 80
Processing chunk 81
Processing chunk 82
Processing chunk 83

In [52]:
df_lcs_windows = df_lcs.copy()
df_lcs_windows['window_id'] = df_lcs_windows.groupby('oid').cumcount() // 200
df_lcs_windows = df_lcs_windows.groupby(["oid", "window_id"]).agg(lambda x: list(x))
df_lcs_windows

                                                                 detected
oid          window_id
ZTF17aaaaabj 0          [True, True, True, False, True, True, True, Tr...  \
             1          [True, True, True, True, True, True, True, Tru...
             2          [True, True, True, True, True, True, True, Tru...
             3          [False, False, False, True, True, True, True, ...
             4          [True, True, True, True, True, True, True, Tru...
...                                                                   ...
ZTF23aboxuyi 0          [False, False, False, False, False, False, Fal...
             1          [False, False, False, False, False, False, Tru...
             2          [False, False, False, False, False, False, Fal...
ZTF23abpbdyh 0          [False, False, False, False, False, False, Fal...
ZTF23abpbuha 0                      [True, False, True, True, True, True]

                                                                      mjd
oid          window_id
ZTF17aaaaabj 0          [58206.16430559987, 58231.14488429995, 58234.1...  \
             1          [58491.22325230017, 58493.221169000026, 58493....
             2          [58806.42067130003, 58806.421134300064, 58806....
             3          [59043.470949099865, 59043.47599539999, 59043....
             4          [59294.158067100216, 59294.19618060021, 59296....
...                                                                   ...
ZTF23aboxuyi 0          [58872.165138899814, 58875.09256940009, 58875....
             1          [59418.46142360009, 59422.43584490009, 59426.4...
             2          [59803.41695600003, 59803.45730319992, 59808.4...
ZTF23abpbdyh 0          [60236.48218750022, 60238.51758099999, 60242.4...
ZTF23abpbuha 0          [60248.48346060002, 60248.50972220022, 60251.4...

                                                      sigma_flux_diff_ujy
oid          window_id
ZTF17aaaaabj 0          [8.440242655407886, 9.70802999032586, 20.01827...  \
             1          [4.335927383739846, 2.337136437970241, 2.61231...
             2          [3.3180606229102576, 3.4208377390652815, 3.416...
             3          [4.021680458844159, 4.18601374614786, 4.365849...
             4          [7.990314418768771, 8.825867966180457, 10.4053...
...                                                                   ...
ZTF23aboxuyi 0          [4.789168652528449, 6.6113980531103085, 4.0210...
             1          [10.31127100662421, 7.095175466434133, 4.76234...
             2          [8.438503543741724, 9.441484804282839, 5.70083...
ZTF23abpbdyh 0          [5.791383450140314, 3.544662523295157, 2.92826...
ZTF23abpbuha 0          [13.62036221217015, 14.48718316429837, 11.4438...

                                                            flux_diff_ujy
oid          window_id
ZTF17aaaaabj 0          [-249.57181969652103, 52.815739767359396, -253...  \
             1          [318.88202860232195, -230.68964424237782, -148...
             2          [-343.69137256798797, -341.49161921565184, -35...
             3          [19.587287226180354, 4.68433612312114, 0.74238...
             4          [196.79623824291224, 301.52910950582645, -288....
...                                                                   ...
ZTF23aboxuyi 0          [1.1547001816474889, -0.84922994538376, 0.5157...
             1          [22.27578010361939, 27.833914276248418, 15.723...
             2          [13.20777222894057, 17.15569121649437, 12.1412...
ZTF23abpbdyh 0          [6.666708298405723, 3.4420276517688113, 3.3954...
ZTF23abpbuha 0          [169.48633315872158, 32.28439269439875, 157.16...

                                                                      fid
oid          window_id
ZTF17aaaaabj 0          [1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ...
             1          [2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ...
             2          [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
             3          [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
             4          [1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
...                                                                   ...
ZTF23aboxuyi 0          [1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, ...
             1          [1, 2, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3, 2, 1, ...
             2          [2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, ...
ZTF23abpbdyh 0                             [2, 2, 1, 2, 1, 2, 1, 1, 1, 2]
ZTF23abpbuha 0                                         [2, 1, 2, 1, 2, 2]

[253017 rows x 5 columns]

In [53]:
windows_merged_df = pd.merge(df_lcs_windows.reset_index(), df_objid_label, on='oid', how='outer')
windows_merged_df

,oid,window_id,detected,mjd,sigma_flux_diff_ujy,flux_diff_ujy,fid,alerceclass
0,ZTF17aaaaabj,0,"[True, True, True, False, True, True, True, Tr...","[58206.16430559987, 58231.14488429995, 58234.1...","[8.440242655407886, 9.70802999032586, 20.01827...","[-249.57181969652103, 52.815739767359396, -253...","[1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ...",RRLc
1,ZTF17aaaaabj,1,"[True, True, True, True, True, True, True, Tru...","[58491.22325230017, 58493.221169000026, 58493....","[4.335927383739846, 2.337136437970241, 2.61231...","[318.88202860232195, -230.68964424237782, -148...","[2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ...",RRLc
2,ZTF17aaaaabj,2,"[True, True, True, True, True, True, True, Tru...","[58806.42067130003, 58806.421134300064, 58806....","[3.3180606229102576, 3.4208377390652815, 3.416...","[-343.69137256798797, -341.49161921565184, -35...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",RRLc
3,ZTF17aaaaabj,3,"[False, False, False, True, True, True, True, ...","[59043.470949099865, 59043.47599539999, 59043....","[4.021680458844159, 4.18601374614786, 4.365849...","[19.587287226180354, 4.68433612312114, 0.74238...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",RRLc
4,ZTF17aaaaabj,4,"[True, True, True, True, True, True, True, Tru...","[59294.158067100216, 59294.19618060021, 59296....","[7.990314418768771, 8.825867966180457, 10.4053...","[196.79623824291224, 301.52910950582645, -288....","[1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",RRLc
...,...,...,...,...,...,...,...,...
253012,ZTF23aboxuyi,0,"[False, False, False, False, False, False, Fal...","[58872.165138899814, 58875.09256940009, 58875....","[4.789168652528449, 6.6113980531103085, 4.0210...","[1.1547001816474889, -0.84922994538376, 0.5157...","[1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, ...",QSO
253013,ZTF23aboxuyi,1,"[False, False, False, False, False, False, Tru...","[59418.46142360009, 59422.43584490009, 59426.4...","[10.31127100662421, 7.095175466434133, 4.76234...","[22.27578010361939, 27.833914276248418, 15.723...","[1, 2, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3, 2, 1, ...",QSO
253014,ZTF23aboxuyi,2,"[False, False, False, False, False, False, Fal...","[59803.41695600003, 59803.45730319992, 59808.4...","[8.438503543741724, 9.441484804282839, 5.70083...","[13.20777222894057, 17.15569121649437, 12.1412...","[2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, ...",QSO
253015,ZTF23abpbdyh,0,"[False, False, False, False, False, False, Fal...","[60236.48218750022, 60238.51758099999, 60242.4...","[5.791383450140314, 3.544662523295157, 2.92826...","[6.666708298405723, 3.4420276517688113, 3.3954...","[2, 2, 1, 2, 1, 2, 1, 1, 1, 2]",CV/Nova
253016,ZTF23abpbuha,0,"[True, False, True, True, True, True]","[60248.48346060002, 60248.50972220022, 60251.4...","[13.62036221217015, 14.48718316429837, 11.4438...","[169.48633315872158, 32.28439269439875, 157.16...","[2, 1, 2, 1, 2, 2]",SNII

In [54]:
final_windows_merged_df = windows_merged_df.set_index(['oid', 'window_id'])
final_windows_merged_df

                                                                 detected
oid          window_id
ZTF17aaaaabj 0          [True, True, True, False, True, True, True, Tr...  \
             1          [True, True, True, True, True, True, True, Tru...
             2          [True, True, True, True, True, True, True, Tru...
             3          [False, False, False, True, True, True, True, ...
             4          [True, True, True, True, True, True, True, Tru...
...                                                                   ...
ZTF23aboxuyi 0          [False, False, False, False, False, False, Fal...
             1          [False, False, False, False, False, False, Tru...
             2          [False, False, False, False, False, False, Fal...
ZTF23abpbdyh 0          [False, False, False, False, False, False, Fal...
ZTF23abpbuha 0                      [True, False, True, True, True, True]

                                                                      mjd
oid          window_id
ZTF17aaaaabj 0          [58206.16430559987, 58231.14488429995, 58234.1...  \
             1          [58491.22325230017, 58493.221169000026, 58493....
             2          [58806.42067130003, 58806.421134300064, 58806....
             3          [59043.470949099865, 59043.47599539999, 59043....
             4          [59294.158067100216, 59294.19618060021, 59296....
...                                                                   ...
ZTF23aboxuyi 0          [58872.165138899814, 58875.09256940009, 58875....
             1          [59418.46142360009, 59422.43584490009, 59426.4...
             2          [59803.41695600003, 59803.45730319992, 59808.4...
ZTF23abpbdyh 0          [60236.48218750022, 60238.51758099999, 60242.4...
ZTF23abpbuha 0          [60248.48346060002, 60248.50972220022, 60251.4...

                                                      sigma_flux_diff_ujy
oid          window_id
ZTF17aaaaabj 0          [8.440242655407886, 9.70802999032586, 20.01827...  \
             1          [4.335927383739846, 2.337136437970241, 2.61231...
             2          [3.3180606229102576, 3.4208377390652815, 3.416...
             3          [4.021680458844159, 4.18601374614786, 4.365849...
             4          [7.990314418768771, 8.825867966180457, 10.4053...
...                                                                   ...
ZTF23aboxuyi 0          [4.789168652528449, 6.6113980531103085, 4.0210...
             1          [10.31127100662421, 7.095175466434133, 4.76234...
             2          [8.438503543741724, 9.441484804282839, 5.70083...
ZTF23abpbdyh 0          [5.791383450140314, 3.544662523295157, 2.92826...
ZTF23abpbuha 0          [13.62036221217015, 14.48718316429837, 11.4438...

                                                            flux_diff_ujy
oid          window_id
ZTF17aaaaabj 0          [-249.57181969652103, 52.815739767359396, -253...  \
             1          [318.88202860232195, -230.68964424237782, -148...
             2          [-343.69137256798797, -341.49161921565184, -35...
             3          [19.587287226180354, 4.68433612312114, 0.74238...
             4          [196.79623824291224, 301.52910950582645, -288....
...                                                                   ...
ZTF23aboxuyi 0          [1.1547001816474889, -0.84922994538376, 0.5157...
             1          [22.27578010361939, 27.833914276248418, 15.723...
             2          [13.20777222894057, 17.15569121649437, 12.1412...
ZTF23abpbdyh 0          [6.666708298405723, 3.4420276517688113, 3.3954...
ZTF23abpbuha 0          [169.48633315872158, 32.28439269439875, 157.16...

                                                                      fid
oid          window_id
ZTF17aaaaabj 0          [1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ...  \
             1          [2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ...
             2          [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
             3          [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
             4          [1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
...                                                                   ...
ZTF23aboxuyi 0          [1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, ...
             1          [1, 2, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3, 2, 1, ...
             2          [2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, ...
ZTF23abpbdyh 0                             [2, 2, 1, 2, 1, 2, 1, 1, 1, 2]
ZTF23abpbuha 0                                         [2, 1, 2, 1, 2, 2]

                       alerceclass
oid          window_id
ZTF17aaaaabj 0                RRLc
             1                RRLc
             2                RRLc
             3                RRLc
             4                RRLc
...                            ...
ZTF23aboxuyi 0                 QSO
             1                 QSO
             2                 QSO
ZTF23abpbdyh 0             CV/Nova
ZTF23abpbuha 0                SNII

[253017 rows x 6 columns]

In [55]:
final_windows_merged_df.groupby(['alerceclass']).count()[['mjd']].sort_values(by='mjd', ascending=False)

                  mjd
alerceclass
EB/EW           22932
RRLab           22005
EA              21830
QSO             21384
RRLc            21038
LPV             20800
AGN             19880
CEP             17584
YSO             16492
RSCVn           15532
SNIa            10542
DSCT            10106
CV/Nova          9772
Blazar           8721
SNII             5184
Periodic-Other   4443
SNIbc            1910
SNIIn            1074
SLSN              636
TDE               425
SNIIb             400
Microlensing      272
ZZ                 55

In [56]:
df_objid_label.groupby(['alerceclass']).count()[['oid']].sort_values(by='oid', ascending=False)

                 oid
alerceclass
LPV             3003
RRLc            3000
EA              3000
EB/EW           3000
RRLab           2999
QSO             2999
YSO             2998
AGN             2998
CEP             2998
SNIa            2996
RSCVn           2578
CV/Nova         1784
DSCT            1659
SNII            1611
Blazar          1478
Periodic-Other  1334
SNIbc            549
SNIIn            301
SLSN             207
SNIIb            130
TDE               87
Microlensing      55
ZZ                13

In [ ]:
def create_windows(lc, max_obs):
    windows = []
    for inicio in range(0, len(lc), max_obs):
        fin = inicio + max_obs
        window = lc.iloc[inicio:fin]
        windows.append(window)
    return windows

def get_windows(df_chunk_filtered, dict_cols):
    list_df_windows = \
        df_chunk_filtered.groupby(dict_cols['oid']).apply(lambda x: create_windows(x, 200))
    
    dict_num_windows = dict()
    lcs_windows = []
    for _, df_windows in list_df_windows.items():
        for j, df_window in enumerate(df_windows):
            dict_num_windows[df_window[dict_cols['oid']].iloc[0]] = j
            df_window[dict_cols['oid']] = df_window[dict_cols['oid']].iloc[0] + '_{}'.format(j)
            lcs_windows.append(df_window)
        
    df_chunk_filtered = pd.concat(lcs_windows)
    return df_chunk_filtered, dict_num_windows


df_a = get_windows(df_lcs, dict_cols)
df_a

(        sigma_flux_diff_ujy  detected  flux_diff_ujy  fid           mjd
 0                  8.440243      True    -249.571820    1  58206.164306  \
 1                  9.708030      True      52.815740    2  58231.144884
 2                 20.018277      True    -253.767498    1  58234.141609
 3                  8.486230     False      41.734686    2  58303.480729
 4                  9.187626      True    -269.465062    1  58304.481157
 ...                     ...       ...            ...  ...           ...
 577238            14.487183     False      32.284393    1  60248.509722
 577239            11.443844      True     157.167240    2  60251.481586
 577240             6.817979      True      47.698061    1  60251.506343
 577241             5.679314      True     184.476503    2  60253.497951
 577242             5.894150      True     182.685772    2  60254.503461

                    oid
 0       ZTF17aaaaabj_0
 1       ZTF17aaaaabj_0
 2       ZTF17aaaaabj_0
 3       ZTF17aaaaabj_0
 4       ZTF17aaaaabj_0
 ...                ...
 577238  ZTF23abpbuha_0
 577239  ZTF23abpbuha_0
 577240  ZTF23abpbuha_0
 577241  ZTF23abpbuha_0
 577242  ZTF23abpbuha_0

 [46321106 rows x 6 columns],
 {'ZTF17aaaaabj': 6,
  'ZTF17aaaaaej': 6,
  'ZTF17aaaaafz': 6,
  'ZTF17aaaaajg': 7,
  'ZTF17aaaaavq': 10,
  'ZTF17aaaaaya': 8,
  'ZTF17aaaabbo': 6,
  'ZTF17aaaabhx': 6,
  'ZTF17aaaacnc': 2,
  'ZTF17aaaactd': 3,
  'ZTF17aaaacth': 3,
  'ZTF17aaaadbq': 5,
  'ZTF17aaaadmx': 5,
  'ZTF17aaaaepx': 5,
  'ZTF17aaaafbz': 8,
  'ZTF17aaaafcd': 10,
  'ZTF17aaaafdm': 9,
  'ZTF17aaaagai': 5,
  'ZTF17aaaaghy': 5,
  'ZTF17aaaagvx': 5,
  'ZTF17aaaagym': 5,
  'ZTF17aaaagyq': 5,
  'ZTF17aaaagyx': 5,
  'ZTF17aaaahsl': 6,
  'ZTF17aaaajey': 11,
  'ZTF17aaaajez': 11,
  'ZTF17aaaajgm': 10,
  'ZTF17aaaajgo': 10,
  'ZTF17aaaajhl': 10,
  'ZTF17aaaajhn': 10,
  'ZTF17aaaajhz': 11,
  'ZTF17aaaajib': 11,
  'ZTF17aaaajim': 10,
  'ZTF17aaaajio': 10,
  'ZTF17aaaajiy': 10,
  'ZTF17aaaajji': 10,
  'ZTF17aaaajka': 8,
  'ZTF17aaaajor': 10,
  'ZTF17aaaajow': 11,
  'ZTF17aaaajoz': 11,
  'ZTF17aaaajqk': 8,
  'ZTF17aaaajqs': 9,
  'ZTF17aaaajqz': 9,
  'ZTF17aaaajra': 9,
  'ZTF17aaaakgn': 7,
  'ZTF17aaaakif': 6,
  'ZTF17aaaakmu': 6,
  'ZTF17aaaamne': 6,
  'ZTF17aaaaniv': 5,
  'ZTF17aaaanlg': 3,
  'ZTF17aaaaoqs': 6,
  'ZTF17aaaaoth': 6,
  'ZTF17aaaaotm': 5,
  'ZTF17aaaaoyi': 6,
  'ZTF17aaaaqil': 6,
  'ZTF17aaaaqmx': 6,
  'ZTF17aaaaqna': 6,
  'ZTF17aaaaqsl': 6,
  'ZTF17aaaaqsr': 6,
  'ZTF17aaaaqsv': 7,
  'ZTF17aaaardi': 6,
  'ZTF17aaaardo': 6,
  'ZTF17aaaargt': 6,
  'ZTF17aaaaxyd': 3,
  'ZTF17aaaaytv': 3,
  'ZTF17aaaazac': 3,
  'ZTF17aaaazlx': 6,
  'ZTF17aaaazmt': 9,
  'ZTF17aaaazob': 9,
  'ZTF17aaaazov': 5,
  'ZTF17aaaaztu': 11,
  'ZTF17aaaazva': 10,
  'ZTF17aaabarf': 5,
  'ZTF17aaabavb': 5,
  'ZTF17aaabbgi': 11,
  'ZTF17aaabbjh': 6,
  'ZTF17aaabbjk': 6,
  'ZTF17aaabbjl': 6,
  'ZTF17aaabcbn': 7,
  'ZTF17aaabcnp': 4,
  'ZTF17aaabcqt': 6,
  'ZTF17aaabdmt': 5,
  'ZTF17aaabesr': 6,
  'ZTF17aaabess': 6,
  'ZTF17aaabfay': 5,
  'ZTF17aaabgdt': 2,
  'ZTF17aaabgfp': 2,
  'ZTF17aaabgfz': 2,
  'ZTF17aaabgha': 0,
  'ZTF17aaabgis': 5,
  'ZTF17aaabgjp': 3,
  'ZTF17aaabgkn': 0,
  'ZTF17aaabkwz': 6,
  'ZTF17aaabpkb': 5,
  'ZTF17aaabril': 10,
  'ZTF17aaabsps': 5,
  'ZTF17aaabtcz': 6,
  'ZTF17aaabtdt': 4,
  'ZTF17aaabtic': 6,
  'ZTF17aaabwti': 6,
  'ZTF17aaabwtj': 6,
  'ZTF17aaabwtl': 6,
  'ZTF17aaabwvd': 6,
  'ZTF17aaabzrf': 1,
  'ZTF17aaabzvl': 2,
  'ZTF17aaacaom': 5,
  'ZTF17aaaccrp': 1,
  'ZTF17aaacdos': 6,
  'ZTF17aaachjt': 3,
  'ZTF17aaachli': 3,
  'ZTF17aaaciwr': 1,
  'ZTF17aaaclph': 5,
  'ZTF17aaacmvk': 5,
  'ZTF17aaadaim': 2,
  'ZTF17aaadaow': 2,
  'ZTF17aaadapn': 3,
  'ZTF17aaadasj': 2,
  'ZTF17aaadata': 3,
  'ZTF17aaadavi': 5,
  'ZTF17aaadavp': 1,
  'ZTF17aaadayn': 6,
  'ZTF17aaadbaf': 6,
  'ZTF17aaadbvh': 6,
  'ZTF17aaaddry': 6,
  'ZTF17aaadhjr': 5,
  'ZTF17aaadjks': 8,
  'ZTF17aaadjrt': 6,
  'ZTF17aaadjul': 8,
  'ZTF17aaadjun': 6,
  'ZTF17aaadkbw': 8,
  'ZTF17aaadned': 3,
  'ZTF17aaadowa': 5,
  'ZTF17aaadoxz': 5,
  'ZTF17aaadpau': 5,
  'ZTF17aaadpcv': 4,
  'ZTF17aaadpkl': 3,
  'ZTF17aaadpqo': 4,
  'ZTF17aaadqae': 3,
  'ZTF17aaadqfm': 4,
  'ZTF17aaadqhs': 3,
  'ZTF17aaadtiy': 5,
  'ZTF17aaadtnn': 4,
  'ZTF17aaaduqv': 9,
  'ZTF17aaadvbq': 9,
  'ZTF17aaadvcd': 9,
  'ZTF17aaadvfh': 5,
  'ZTF17aaadvfi': 5,
  'ZTF17aaadxdb': 6,
  'ZTF17aaadxpb': 5,
  'ZTF17aaadxxw': 5,
  'ZTF17aaadxyb': 5,
  'ZTF17aaadxyr': 7,
  'ZTF17aaadxzc': 5,
  'ZTF17aaadxzf': 5,
  'ZTF17aaadxzy': 8,
  'ZTF17aaadxzz': 8,
  'ZTF17aaadyay': 7,
  'ZTF17aaadyca': 8,
  'ZTF17aaadyct': 7,
  'ZTF17aaadynh': 7,
  'ZTF17aaadynj': 7,
  'ZTF17aaadynk': 5,
  'ZTF17aaadynp': 7,
  'ZTF17aaadypt': 8,
  'ZTF17aaadyqb': 8,
  'ZTF17aaadyqs': 8,
  'ZTF17aaadyro': 7,
  'ZTF17aaadytr': 6,
  'ZTF17aaadyty': 6,
  'ZTF17aaadyug': 7,
  'ZTF17aaadyvo': 7,
  'ZTF17aaadywb': 7,
  'ZTF17aaadyxi': 7,
  'ZTF17aaadyxj': 8,
  'ZTF17aaadyxn': 8,
  'ZTF17aaadyyf': 5,
  'ZTF17aaadyyg': 8,
  'ZTF17aaadyzd': 6,
  'ZTF17aaadyzg': 6,
  'ZTF17aaadyzl': 5,
  'ZTF17aaadyzt': 6,
  'ZTF17aaadyzu': 6,
  'ZTF17aaadyzz': 8,
  'ZTF17aaadzaa': 8,
  'ZTF17aaadzce': 6,
  'ZTF17aaadzcj': 6,
  'ZTF17aaadzcs': 8,
  'ZTF17aaadzda': 5,
  'ZTF17aaadzef': 8,
  'ZTF17aaadzfa': 7,
  'ZTF17aaadzhb': 8,
  'ZTF17aaadzhe': 7,
  'ZTF17aaadzho': 1,
  'ZTF17aaadzjs': 8,
  'ZTF17aaadzlk': 8,
  'ZTF17aaadzlm': 8,
  'ZTF17aaadzlo': 6,
  'ZTF17aaadzlp': 6,
  'ZTF17aaadzlq': 7,
  'ZTF17aaadzpr': 8,
  'ZTF17aaadzqg': 6,
  'ZTF17aaadzqp': 7,
  'ZTF17aaadzrk': 7,
  'ZTF17aaadzrt': 6,
  'ZTF17aaaeabr': 7,
  'ZTF17aaaeaez': 6,
  'ZTF17aaaeafk': 7,
  'ZTF17aaaeagm': 7,
  'ZTF17aaaeahk': 6,
  'ZTF17aaaeaif': 6,
  'ZTF17aaaeajd': 11,
  'ZTF17aaaeall': 3,
  'ZTF17aaaealn': 10,
  'ZTF17aaaeamc': 10,
  'ZTF17aaaeamj': 2,
  'ZTF17aaaeamk': 2,
  'ZTF17aaaeanw': 8,
  'ZTF17aaaeany': 6,
  'ZTF17aaaeaoa': 6,
  'ZTF17aaaeaow': 10,
  'ZTF17aaaeapf': 6,
  'ZTF17aaaeapo': 6,
  'ZTF17aaaeaqs': 6,
  'ZTF17aaaearn': 10,
  'ZTF17aaaearu': 6,
  'ZTF17aaaeasn': 8,
  'ZTF17aaaeawl': 8,
  'ZTF17aaaeawm': 8,
  'ZTF17aaaeayf': 6,
  'ZTF17aaaeayj': 6,
  'ZTF17aaaeayl': 6,
  'ZTF17aaaeayo': 6,
  'ZTF17aaaeayp': 6,
  'ZTF17aaaeayr': 6,
  'ZTF17aaaeaza': 6,
  'ZTF17aaaebam': 6,
  'ZTF17aaaebbs': 6,
  'ZTF17aaaebcr': 6,
  'ZTF17aaaebdw': 6,
  'ZTF17aaaebeh': 6,
  'ZTF17aaaebhk': 8,
  'ZTF17aaaebkt': 10,
  'ZTF17aaaebna': 6,
  'ZTF17aaaeboq': 6,
  'ZTF17aaaebpc': 6,
  'ZTF17aaaebps': 9,
  'ZTF17aaaebwt': 6,
  'ZTF17aaaeccg': 6,
  'ZTF17aaaeceb': 7,
  'ZTF17aaaecfd': 7,
  'ZTF17aaaecfh': 7,
  'ZTF17aaaecfu': 7,
  'ZTF17aaaecgi': 7,
  'ZTF17aaaecgm': 6,
  'ZTF17aaaechg': 7,
  'ZTF17aaaecij': 8,
  'ZTF17aaaecik': 8,
  'ZTF17aaaecil': 8,
  'ZTF17aaaecin': 7,
  'ZTF17aaaecjb': 8,
  'ZTF17aaaeckh': 7,
  'ZTF17aaaeckw': 8,
  'ZTF17aaaecky': 8,
  'ZTF17aaaecla': 8,
  'ZTF17aaaeclg': 4,
  'ZTF17aaaecmi': 7,
  'ZTF17aaaecni': 7,
  'ZTF17aaaecok': 7,
  'ZTF17aaaecol': 8,
  'ZTF17aaaecor': 7,
  'ZTF17aaaecou': 7,
  'ZTF17aaaecsq': 3,
  'ZTF17aaaectt': 7,
  'ZTF17aaaectv': 7,
  'ZTF17aaaecty': 7,
  'ZTF17aaaecvb': 7,
  'ZTF17aaaecvc': 7,
  'ZTF17aaaecvj': 7,
  'ZTF17aaaecvr': 8,
  'ZTF17aaaecwh': 8,
  'ZTF17aaaecwi': 8,
  'ZTF17aaaecwl': 7,
  'ZTF17aaaecyn': 8,
  'ZTF17aaaecyw': 8,
  'ZTF17aaaeczp': 4,
  'ZTF17aaaedat': 7,
  'ZTF17aaaedaz': 8,
  'ZTF17aaaedbh': 8,
  'ZTF17aaaedde': 8,
  'ZTF17aaaedeq': 8,
  'ZTF17aaaedez': 8,
  'ZTF17aaaedfa': 8,
  'ZTF17aaaedfm': 8,
  'ZTF17aaaedfo': 7,
  'ZTF17aaaedge': 7,
  'ZTF17aaaedjr': 7,
  'ZTF17aaaedlv': 7,
  'ZTF17aaaednc': 7,
  'ZTF17aaaedoi': 6,
  'ZTF17aaaedpn': 8,
  'ZTF17aaaedpq': 8,
  'ZTF17aaaedqx': 7,
  'ZTF17aaaedrk': 6,
  'ZTF17aaaedrm': 8,
  'ZTF17aaaedtj': 8,
  'ZTF17aaaeduf': 8,
  'ZTF17aaaeduo': 6,
  'ZTF17aaaeduv': 7,
  'ZTF17aaaedvi': 7,
  'ZTF17aaaedwv': 8,
  'ZTF17aaaedyv': 7,
  'ZTF17aaaedyy': 7,
  'ZTF17aaaeeck': 8,
  'ZTF17aaaeecs': 3,
  'ZTF17aaaeeix': 7,
  'ZTF17aaaeela': 6,
  'ZTF17aaaeemj': 7,
  'ZTF17aaaeenw': 7,
  'ZTF17aaaeeny': 7,
  'ZTF17aaaeepy': 7,
  'ZTF17aaaeeqq': 8,
  'ZTF17aaaeert': 6,
  'ZTF17aaaeesi': 8,
  'ZTF17aaaeeth': 8,
  'ZTF17aaaeeto': 8,
  'ZTF17aaaegdy': 3,
  'ZTF17aaaehca': 8,
  'ZTF17aaaehgv': 7,
  'ZTF17aaaehmf': 6,
  'ZTF17aaaehmk': 9,
  'ZTF17aaaehoa': 8,
  'ZTF17aaaehqt': 7,
  'ZTF17aaaehsq': 7,
  'ZTF17aaaehsx': 6,
  'ZTF17aaaehta': 7,
  'ZTF17aaaehtj': 9,
  'ZTF17aaaehuf': 9,
  'ZTF17aaaehve': 6,
  'ZTF17aaaehvh': 9,
  'ZTF17aaaehvi': 9,
  'ZTF17aaaehvr': 9,
  'ZTF17aaaehwn': 9,
  'ZTF17aaaehwo': 9,
  'ZTF17aaaehxn': 6,
  'ZTF17aaaehxy': 6,
  'ZTF17aaaehye': 6,
  'ZTF17aaaehyw': 9,
  'ZTF17aaaehyx': 9,
  'ZTF17aaaehzb': 9,
  'ZTF17aaaehzd': 6,
  'ZTF17aaaehzz': 11,
  'ZTF17aaaeiaf': 10,
  'ZTF17aaaeiat': 9,
  'ZTF17aaaeicp': 8,
  'ZTF17aaaeido': 7,
  'ZTF17aaaeiev': 8,
  'ZTF17aaaeiex': 8,
  'ZTF17aaaeiez': 7,
  'ZTF17aaaeifc': 8,
  'ZTF17aaaeiff': 8,
  'ZTF17aaaeifx': 8,
  'ZTF17aaaeihg': 8,
  'ZTF17aaaeiis': 8,
  'ZTF17aaaeiiz': 11,
  'ZTF17aaaeijf': 8,
  'ZTF17aaaeijn': 8,
  'ZTF17aaaeikn': 7,
  'ZTF17aaaeiks': 7,
  'ZTF17aaaeikt': 7,
  'ZTF17aaaeikw': 7,
  'ZTF17aaaeiln': 7,
  'ZTF17aaaeilu': 10,
  'ZTF17aaaeipd': 6,
  'ZTF17aaaeiql': 6,
  'ZTF17aaaeirt': 7,
  'ZTF17aaaeisc': 6,
  'ZTF17aaaeisu': 5,
  'ZTF17aaaeitb': 8,
  'ZTF17aaaeivl': 7,
  'ZTF17aaaejaq': 11,
  'ZTF17aaaejcr': 8,
  'ZTF17aaaejek': 11,
  'ZTF17aaaejfe': 7,
  'ZTF17aaaejqa': 9,
  'ZTF17aaaejtu': 7,
  'ZTF17aaaejvs': 8,
  'ZTF17aaaejwm': 8,
  'ZTF17aaaekfn': 8,
  'ZTF17aaaekge': 8,
  'ZTF17aaaekkm': 7,
  'ZTF17aaaekmt': 7,
  'ZTF17aaaeknj': 7,
  'ZTF17aaaekoc': 8,
  'ZTF17aaaeksz': 7,
  'ZTF17aaaekus': 5,
  'ZTF17aaaekvi': 5,
  'ZTF17aaaekyg': 7,
  'ZTF17aaaekyn': 5,
  'ZTF17aaaekzr': 5,
  'ZTF17aaaelaa': 8,
  'ZTF17aaaelhh': 7,
  'ZTF17aaaemzh': 7,
  'ZTF17aaaeneg': 8,
  'ZTF17aaaenfh': 8,
  'ZTF17aaaenfn': 8,
  'ZTF17aaaengk': 9,
  'ZTF17aaaengo': 9,
  'ZTF17aaaenhc': 8,
  'ZTF17aaaenhs': 6,
  'ZTF17aaaenkh': 7,
  'ZTF17aaaenmh': 7,
  'ZTF17aaaenml': 8,
  'ZTF17aaaennm': 7,
  'ZTF17aaaennv': 4,
  'ZTF17aaaenok': 9,
  'ZTF17aaaenoo': 9,
  'ZTF17aaaenrr': 7,
  'ZTF17aaaentq': 5,
  'ZTF17aaaenup': 6,
  'ZTF17aaaenwn': 6,
  'ZTF17aaaenxn': 6,
  'ZTF17aaaeocl': 6,
  'ZTF17aaaeoeh': 6,
  'ZTF17aaaeoei': 6,
  'ZTF17aaaeoer': 6,
  'ZTF17aaaeoeu': 6,
  'ZTF17aaaeoew': 6,
  'ZTF17aaaeoey': 6,
  'ZTF17aaaeojh': 6,
  'ZTF17aaaeokm': 6,
  'ZTF17aaaeokw': 6,
  'ZTF17aaaeomy': 6,
  'ZTF17aaaeosv': 1,
  'ZTF17aaaeoum': 5,
  'ZTF17aaaeowa': 6,
  'ZTF17aaaeoxx': 6,
  'ZTF17aaaepdv': 6,
  'ZTF17aaaeqag': 5,
  'ZTF17aaaeqec': 3,
  'ZTF17aaaeqgy': 5,
  'ZTF17aaaeqhm': 6,
  'ZTF17aaaeqxk': 3,
  'ZTF17aaaerjh': 3,
  'ZTF17aaaesno': 9,
  'ZTF17aaaesrm': 7,
  'ZTF17aaaessu': 7,
  'ZTF17aaaesvh': 7,
  'ZTF17aaaeszr': 7,
  'ZTF17aaaeuky': 9,
  'ZTF17aaaeuoq': 5,
  'ZTF17aaaeupv': 6,
  'ZTF17aaaeupz': 9,
  'ZTF17aaaeuqg': 7,
  'ZTF17aaaeuqk': 7,
  'ZTF17aaaeurt': 6,
  'ZTF17aaaeusb': 6,
  'ZTF17aaaeutf': 6,
  'ZTF17aaaeuub': 8,
  'ZTF17aaaeuui': 6,
  'ZTF17aaaeuvb': 6,
  'ZTF17aaaeuvd': 6,
  'ZTF17aaaeuvf': 6,
  'ZTF17aaaevgx': 8,
  'ZTF17aaaeviy': 7,
  'ZTF17aaaevxe': 8,
  'ZTF17aaaevxo': 6,
  'ZTF17aaaevye': 4,
  'ZTF17aaaewaj': 2,
  'ZTF17aaaewcw': 5,
  'ZTF17aaaewjv': 5,
  'ZTF17aaaewmc': 6,
  'ZTF17aaaewmi': 5,
  'ZTF17aaaewoq': 5,
  'ZTF17aaaewpx': 5,
  'ZTF17aaaewqh': 5,
  'ZTF17aaaexha': 6,
  'ZTF17aaaexhk': 6,
  'ZTF17aaaeznw': 7,
  'ZTF17aaaezrs': 4,
  'ZTF17aaafakz': 5,
  'ZTF17aaafcun': 5,
  'ZTF17aaafffc': 4,
  'ZTF17aaafglk': 4,
  'ZTF17aaafgst': 5,
  'ZTF17aaafhcw': 5,
  'ZTF17aaafhkd': 6,
  'ZTF17aaafhpv': 6,
  'ZTF17aaafian': 6,
  'ZTF17aaafias': 6,
  'ZTF17aaafibe': 6,
  'ZTF17aaafidd': 6,
  'ZTF17aaafidt': 8,
  'ZTF17aaafidy': 8,
  'ZTF17aaafieu': 8,
  'ZTF17aaafifg': 8,
  'ZTF17aaafifi': 8,
  'ZTF17aaafihc': 8,
  'ZTF17aaafijq': 8,
  'ZTF17aaafikw': 8,
  'ZTF17aaafild': 8,
  'ZTF17aaafiml': 6,
  'ZTF17aaafios': 7,
  'ZTF17aaafipx': 6,
  'ZTF17aaafiut': 8,
  'ZTF17aaafivv': 6,
  'ZTF17aaafiwv': 7,
  'ZTF17aaafiww': 7,
  'ZTF17aaafizv': 6,
  'ZTF17aaafjai': 4,
  'ZTF17aaafjsi': 9,
  'ZTF17aaafkxc': 6,
  'ZTF17aaaflfb': 4,
  'ZTF17aaaflwj': 6,
  'ZTF17aaafnqq': 6,
  'ZTF17aaafnqr': 6,
  'ZTF17aaafoon': 4,
  'ZTF17aaafqiy': 5,
  'ZTF17aaafrmf': 5,
  'ZTF17aaaftak': 7,
  'ZTF17aaaftaw': 7,
  'ZTF17aaaftbr': 7,
  'ZTF17aaaftbz': 6,
  'ZTF17aaaftdo': 5,
  'ZTF17aaaftdz': 5,
  'ZTF17aaafuog': 6,
  'ZTF17aaafuoi': 6,
  'ZTF17aaafupm': 6,
  'ZTF17aaafupp': 6,
  'ZTF17aaafvmh': 7,
  'ZTF17aaafwnr': 3,
  'ZTF17aaafwou': 5,
  'ZTF17aaafxbb': 6,
  'ZTF17aaafxex': 6,
  'ZTF17aaafxjp': 5,
  'ZTF17aaafxks': 5,
  'ZTF17aaafxll': 6,
  'ZTF17aaafxya': 6,
  'ZTF17aaafyci': 5,
  'ZTF17aaafyfh': 5,
  'ZTF17aaafyis': 7,
  'ZTF17aaafyiy': 8,
  'ZTF17aaafynz': 8,
  'ZTF17aaafyoa': 7,
  'ZTF17aaafypx': 8,
  'ZTF17aaafyux': 8,
  'ZTF17aaafyxs': 7,
  'ZTF17aaafzma': 8,
  'ZTF17aaagabc': 3,
  'ZTF17aaagabm': 8,
  'ZTF17aaagabt': 2,
  'ZTF17aaagadx': 3,
  'ZTF17aaagapg': 4,
  'ZTF17aaagapu': 0,
  'ZTF17aaagaqa': 0,
  'ZTF17aaagari': 2,
  'ZTF17aaagath': 2,
  'ZTF17aaagatm': 2,
  'ZTF17aaagato': 2,
  'ZTF17aaagazp': 2,
  'ZTF17aaagbfr': 2,
  'ZTF17aaagbfs': 2,
  'ZTF17aaagbga': 2,
  'ZTF17aaagbjq': 4,
  'ZTF17aaagbzg': 3,
  'ZTF17aaagccm': 3,
  'ZTF17aaagcup': 2,
  'ZTF17aaageae': 4,
  'ZTF17aaaggvw': 2,
  'ZTF17aaaghhi': 7,
  'ZTF17aaaghhm': 4,
  'ZTF17aaaghhn': 7,
  'ZTF17aaagiaw': 3,
  'ZTF17aaagily': 3,
  'ZTF17aaaglec': 9,
  'ZTF17aaaglhj': 9,
  'ZTF17aaaglie': 9,
  'ZTF17aaaglug': 7,
  'ZTF17aaagmnf': 9,
  'ZTF17aaagnwk': 2,
  'ZTF17aaagnwn': 2,
  'ZTF17aaagpcv': 5,
  'ZTF17aaagpsz': 5,
  'ZTF17aaagptx': 5,
  'ZTF17aaagqfz': 5,
  'ZTF17aaagqib': 5,
  'ZTF17aaagqjv': 3,
  'ZTF17aaagqlp': 6,
  'ZTF17aaagqwm': 6,
  'ZTF17aaagqyv': 6,
  'ZTF17aaagrad': 6,
  'ZTF17aaagrbi': 6,
  'ZTF17aaagrdx': 6,
  'ZTF17aaagrgh': 6,
  'ZTF17aaagrhs': 7,
  'ZTF17aaagril': 6,
  'ZTF17aaagrir': 6,
  'ZTF17aaagrjg': 6,
  'ZTF17aaagrjh': 8,
  'ZTF17aaagrju': 7,
  'ZTF17aaagrjv': 7,
  'ZTF17aaagrkk': 6,
  'ZTF17aaagrko': 5,
  'ZTF17aaagrkx': 8,
  'ZTF17aaagrly': 7,
  'ZTF17aaagrmg': 7,
  'ZTF17aaagrmi': 6,
  'ZTF17aaagrnu': 7,
  'ZTF17aaagroa': 9,
  'ZTF17aaagroo': 7,
  'ZTF17aaagrpb': 8,
  'ZTF17aaagrpt': 8,
  'ZTF17aaagrqb': 8,
  'ZTF17aaagrqv': 2,
  'ZTF17aaagrrm': 2,
  'ZTF17aaagrrw': 7,
  'ZTF17aaagrry': 3,
  'ZTF17aaagrsl': 8,
  'ZTF17aaagrtg': 8,
  'ZTF17aaagrtk': 8,
  'ZTF17aaagrug': 2,
  'ZTF17aaagryq': 2,
  'ZTF17aaagtfy': 5,
  'ZTF17aaagthd': 4,
  'ZTF17aaagtzz': 5,
  'ZTF17aaagukn': 4,
  'ZTF17aaaguly': 1,
  'ZTF17aaaguql': 5,
  'ZTF17aaagvif': 5,
  'ZTF17aaagvih': 5,
  'ZTF17aaagvii': 5,
  'ZTF17aaagvij': 5,
  'ZTF17aaagvil': 5,
  'ZTF17aaagvim': 5,
  'ZTF17aaagvip': 5,
  'ZTF17aaagvir': 5,
  'ZTF17aaagvly': 3,
  'ZTF17aaagvnm': 3,
  'ZTF17aaagvoz': 4,
  'ZTF17aaagvsz': 4,
  'ZTF17aaagwok': 5,
  'ZTF17aaagxad': 3,
  'ZTF17aaagyfy': 2,
  'ZTF17aaagygm': 2,
  'ZTF17aaagynp': 2,
  'ZTF17aaagyop': 2,
  'ZTF17aaagyqw': 3,
  'ZTF17aaagyuc': 3,
  'ZTF17aaagzbt': 3,
  'ZTF17aaagzel': 3,
  'ZTF17aaahcwy': 4,
  'ZTF17aaahdwp': 4,
  'ZTF17aaaheem': 5,
  'ZTF17aaahefy': 3,
  'ZTF17aaahehi': 5,
  'ZTF17aaaheln': 1,
  'ZTF17aaahemg': 6,
  'ZTF17aaahepe': 5,
  'ZTF17aaahepx': 5,
  'ZTF17aaaherw': 5,
  'ZTF17aaahesa': 6,
  'ZTF17aaahevh': 1,
  'ZTF17aaahezq': 5,
  'ZTF17aaahfhn': 4,
  'ZTF17aaahfho': 6,
  'ZTF17aaahfic': 5,
  'ZTF17aaahfif': 3,
  'ZTF17aaahflv': 4,
  'ZTF17aaahgfs': 5,
  'ZTF17aaahgie': 7,
  'ZTF17aaahgsv': 6,
  'ZTF17aaahinf': 3,
  'ZTF17aaahitl': 5,
  'ZTF17aaahmid': 4,
  'ZTF17aaahmjo': 4,
  'ZTF17aaahmmm': 5,
  'ZTF17aaahmpb': 5,
  'ZTF17aaahmum': 5,
  'ZTF17aaahmxl': 6,
  'ZTF17aaahnbq': 1,
  'ZTF17aaahnsb': 5,
  'ZTF17aaahqlu': 5,
  'ZTF17aaahqnd': 5,
  'ZTF17aaahria': 3,
  'ZTF17aaahrmb': 3,
  'ZTF17aaahrrt': 2,
  'ZTF17aaahrsm': 0,
  'ZTF17aaahrta': 2,
  'ZTF17aaahrug': 1,
  'ZTF17aaahrvt': 1,
  'ZTF17aaahrwd': 0,
  'ZTF17aaahrwe': 0,
  'ZTF17aaahrwf': 2,
  'ZTF17aaahrwg': 0,
  'ZTF17aaahrwh': 0,
  'ZTF17aaahrwi': 0,
  'ZTF17aaahrwl': 2,
  'ZTF17aaahrxm': 2,
  'ZTF17aaahrya': 1,
  'ZTF17aaahryv': 3,
  'ZTF17aaahryw': 3,
  'ZTF17aaahryy': 3,
  'ZTF17aaahryz': 3,
  'ZTF17aaahrza': 3,
  'ZTF17aaahrzb': 3,
  'ZTF17aaahrzk': 3,
  'ZTF17aaahsaa': 3,
  'ZTF17aaahshu': 2,
  'ZTF17aaahsin': 2,
  'ZTF17aaahsqu': 0,
  'ZTF17aaahszr': 3,
  'ZTF17aaahtcq': 3,
  'ZTF17aaahtdr': 3,
  'ZTF17aaahtep': 3,
  'ZTF17aaahtog': 4,
  'ZTF17aaahwwy': 4,
  'ZTF17aaahxnm': 5,
  'ZTF17aaahygc': 3,
  'ZTF17aaahyrh': 7,
  'ZTF17aaahyrz': 9,
  'ZTF17aaahzsk': 6,
  'ZTF17aaahzsv': 4,
  'ZTF17aaahzut': 6,
  'ZTF17aaaiapr': 4,
  'ZTF17aaaiapz': 3,
  'ZTF17aaaiawf': 5,
  'ZTF17aaaiawg': 4,
  'ZTF17aaaibas': 6,
  'ZTF17aaaibga': 5,
  'ZTF17aaaibgb': 5,
  'ZTF17aaaidjf': 3,
  'ZTF17aaaidwk': 5,
  'ZTF17aaaidzt': 4,
  'ZTF17aaaielp': 3,
  'ZTF17aaaigdn': 5,
  'ZTF17aaaigwu': 3,
  'ZTF17aaaihcq': 4,
  'ZTF17aaaihpk': 4,
  'ZTF17aaaiidr': 4,
  'ZTF17aaaikkr': 6,
  'ZTF17aaaikuu': 6,
  'ZTF17aaaikvf': 6,
  'ZTF17aaailff': 4,
  'ZTF17aaailib': 3,
  'ZTF17aaailio': 4,
  'ZTF17aaailjd': 6,
  'ZTF17aaaillb': 3,
  'ZTF17aaailzk': 5,
  'ZTF17aaaimym': 4,
  'ZTF17aaaindr': 4,
  'ZTF17aaainmx': 5,
  'ZTF17aaainxv': 3,
  'ZTF17aaaiosv': 4,
  'ZTF17aaaipbw': 7,
  'ZTF17aaaipcy': 6,
  'ZTF17aaaipza': 7,
  'ZTF17aaaiqdu': 8,
  'ZTF17aaairbu': 9,
  'ZTF17aaairfp': 7,
  'ZTF17aaairkd': 6,
  'ZTF17aaairyo': 5,
  'ZTF17aaaitdn': 3,
  'ZTF17aaaitpz': 5,
  'ZTF17aaaitrs': 5,
  'ZTF17aaaiuwk': 7,
  'ZTF17aaaiuxn': 4,
  'ZTF17aaaivav': 4,
  'ZTF17aaaiwfl': 4,
  'ZTF17aaaiynp': 3,
  'ZTF17aaaiyrx': 4,
  'ZTF17aaaizcd': 4,
  'ZTF17aaaizfe': 4,
  'ZTF17aaaizfs': 1,
  'ZTF17aaaizfv': 4,
  'ZTF17aaaiziw': 4,
  'ZTF17aaaizxf': 5,
  'ZTF17aaajahq': 5,
  'ZTF17aaajaka': 4,
  'ZTF17aaajazz': 5,
  'ZTF17aaajbbv': 0,
  'ZTF17aaajbez': 6,
  'ZTF17aaajeks': 4,
  'ZTF17aaajeyp': 4,
  'ZTF17aaajfab': 5,
  'ZTF17aaajfbk': 4,
  'ZTF17aaajffd': 6,
  'ZTF17aaajfgr': 6,
  'ZTF17aaajfhh': 7,
  'ZTF17aaajfil': 6,
  'ZTF17aaajfxl': 4,
  'ZTF17aaajgdh': 3,
  'ZTF17aaajhgk': 0,
  'ZTF17aaajhib': 3,
  'ZTF17aaajhzf': 2,
  'ZTF17aaajigj': 5,
  'ZTF17aaajigv': 5,
  'ZTF17aaajigz': 5,
  'ZTF17aaajihk': 6,
  'ZTF17aaajijc': 7,
  'ZTF17aaajijv': 4,
  'ZTF17aaajikw': 7,
  'ZTF17aaajjee': 2,
  'ZTF17aaajjkd': 2,
  'ZTF17aaajjpk': 8,
  'ZTF17aaajjpo': 8,
  'ZTF17aaajjqm': 8,
  'ZTF17aaajjsv': 6,
  'ZTF17aaajkzm': 6,
  'ZTF17aaajlbs': 5,
  'ZTF17aaajlfr': 5,
  'ZTF17aaajlfv': 4,
  'ZTF17aaajlfw': 3,
  'ZTF17aaajllf': 2,
  'ZTF17aaajlmi': 3,
  'ZTF17aaajlnf': 3,
  'ZTF17aaajmct': 2,
  'ZTF17aaajmdq': 5,
  'ZTF17aaajmee': 3,
  'ZTF17aaajmef': 4,
  'ZTF17aaajmsc': 7,
  'ZTF17aaajmse': 7,
  'ZTF17aaajmsl': 8,
  'ZTF17aaajmth': 7,
  'ZTF17aaajmxe': 6,
  'ZTF17aaajmxw': 3,
  'ZTF17aaajnkm': 6,
  'ZTF17aaajnlh': 8,
  'ZTF17aaajnli': 7,
  'ZTF17aaajnnm': 7,
  'ZTF17aaajnnr': 8,
  'ZTF17aaajnrq': 3,
  'ZTF17aaajocp': 7,
  'ZTF17aaajoeu': 6,
  'ZTF17aaajomh': 3,
  'ZTF17aaajpfk': 3,
  'ZTF17aaajpfx': 3,
  'ZTF17aaajqjm': 4,
  'ZTF17aaajqkc': 6,
  'ZTF17aaajqkd': 6,
  'ZTF17aaajrfx': 4,
  'ZTF17aaajrob': 6,
  'ZTF17aaajrrz': 5,
  'ZTF17aaajrva': 6,
  'ZTF17aaajrwc': 6,
  'ZTF17aaajrwd': 6,
  'ZTF17aaajrwh': 6,
  'ZTF17aaajrxk': 7,
  'ZTF17aaajrxn': 7,
  'ZTF17aaajsge': 5,
  'ZTF17aaajsia': 5,
  'ZTF17aaajsnf': 5,
  'ZTF17aaajsrm': 6,
  'ZTF17aaajsrn': 6,
  'ZTF17aaajsrr': 6,
  'ZTF17aaajssv': 6,
  'ZTF17aaajsta': 6,
  'ZTF17aaajstg': 6,
  'ZTF17aaajsui': 6,
  'ZTF17aaajsum': 6,
  'ZTF17aaajsxf': 8,
  'ZTF17aaajsxy': 8,
  'ZTF17aaajsxz': 8,
  'ZTF17aaajsyg': 4,
  'ZTF17aaajtag': 6,
  'ZTF17aaajtbf': 5,
  'ZTF17aaajtbg': 7,
  'ZTF17aaajtcq': 8,
  'ZTF17aaajtfr': 7,
  'ZTF17aaajtfx': 7,
  'ZTF17aaajtgd': 7,
  'ZTF17aaajtlm': 5,
  'ZTF17aaajtva': 5,
  'ZTF17aaajtwr': 5,
  'ZTF17aaajvds': 3,
  'ZTF17aaajvzg': 6,
  'ZTF17aaajwzg': 3,
  'ZTF17aaajzet': 5,
  'ZTF17aaakame': 6,
  'ZTF17aaakbca': 6,
  'ZTF17aaakbit': 6,
  'ZTF17aaakbvl': 6,
  'ZTF17aaakccv': 4,
  'ZTF17aaakcno': 7,
  'ZTF17aaakcol': 7,
  'ZTF17aaakcou': 6,
  'ZTF17aaakebb': 3,
  'ZTF17aaakecv': 3,
  'ZTF17aaakfdt': 3,
  'ZTF17aaakfma': 5,
  'ZTF17aaakfmr': 5,
  'ZTF17aaakfoc': 5,
  'ZTF17aaakfos': 5,
  'ZTF17aaakfrg': 6,
  'ZTF17aaakguh': 6,

In [ ]:
df_a[0]

,sigma_flux_diff_ujy,detected,flux_diff_ujy,fid,mjd,oid
0,8.440243,True,-249.571820,1,58206.164306,ZTF17aaaaabj_0
1,9.708030,True,52.815740,2,58231.144884,ZTF17aaaaabj_0
2,20.018277,True,-253.767498,1,58234.141609,ZTF17aaaaabj_0
3,8.486230,False,41.734686,2,58303.480729,ZTF17aaaaabj_0
4,9.187626,True,-269.465062,1,58304.481157,ZTF17aaaaabj_0
...,...,...,...,...,...,...
577238,14.487183,False,32.284393,1,60248.509722,ZTF23abpbuha_0
577239,11.443844,True,157.167240,2,60251.481586,ZTF23abpbuha_0
577240,6.817979,True,47.698061,1,60251.506343,ZTF23abpbuha_0
577241,5.679314,True,184.476503,2,60253.497951,ZTF23abpbuha_0
577242,5.894150,True,182.685772,2,60254.503461,ZTF23abpbuha_0

In [ ]:
df_a[1]

{'ZTF17aaaaabj': 6,
 'ZTF17aaaaaej': 6,
 'ZTF17aaaaafz': 6,
 'ZTF17aaaaajg': 7,
 'ZTF17aaaaavq': 10,
 'ZTF17aaaaaya': 8,
 'ZTF17aaaabbo': 6,
 'ZTF17aaaabhx': 6,
 'ZTF17aaaacnc': 2,
 'ZTF17aaaactd': 3,
 'ZTF17aaaacth': 3,
 'ZTF17aaaadbq': 5,
 'ZTF17aaaadmx': 5,
 'ZTF17aaaaepx': 5,
 'ZTF17aaaafbz': 8,
 'ZTF17aaaafcd': 10,
 'ZTF17aaaafdm': 9,
 'ZTF17aaaagai': 5,
 'ZTF17aaaaghy': 5,
 'ZTF17aaaagvx': 5,
 'ZTF17aaaagym': 5,
 'ZTF17aaaagyq': 5,
 'ZTF17aaaagyx': 5,
 'ZTF17aaaahsl': 6,
 'ZTF17aaaajey': 11,
 'ZTF17aaaajez': 11,
 'ZTF17aaaajgm': 10,
 'ZTF17aaaajgo': 10,
 'ZTF17aaaajhl': 10,
 'ZTF17aaaajhn': 10,
 'ZTF17aaaajhz': 11,
 'ZTF17aaaajib': 11,
 'ZTF17aaaajim': 10,
 'ZTF17aaaajio': 10,
 'ZTF17aaaajiy': 10,
 'ZTF17aaaajji': 10,
 'ZTF17aaaajka': 8,
 'ZTF17aaaajor': 10,
 'ZTF17aaaajow': 11,
 'ZTF17aaaajoz': 11,
 'ZTF17aaaajqk': 8,
 'ZTF17aaaajqs': 9,
 'ZTF17aaaajqz': 9,
 'ZTF17aaaajra': 9,
 'ZTF17aaaakgn': 7,
 'ZTF17aaaakif': 6,
 'ZTF17aaaakmu': 6,
 'ZTF17aaaamne': 6,
 'ZTF17aaaaniv': 5,
 'ZTF17aaaanlg': 3,
 'ZTF17aaaaoqs': 6,
 'ZTF17aaaaoth': 6,
 'ZTF17aaaaotm': 5,
 'ZTF17aaaaoyi': 6,
 'ZTF17aaaaqil': 6,
 'ZTF17aaaaqmx': 6,
 'ZTF17aaaaqna': 6,
 'ZTF17aaaaqsl': 6,
 'ZTF17aaaaqsr': 6,
 'ZTF17aaaaqsv': 7,
 'ZTF17aaaardi': 6,
 'ZTF17aaaardo': 6,
 'ZTF17aaaargt': 6,
 'ZTF17aaaaxyd': 3,
 'ZTF17aaaaytv': 3,
 'ZTF17aaaazac': 3,
 'ZTF17aaaazlx': 6,
 'ZTF17aaaazmt': 9,
 'ZTF17aaaazob': 9,
 'ZTF17aaaazov': 5,
 'ZTF17aaaaztu': 11,
 'ZTF17aaaazva': 10,
 'ZTF17aaabarf': 5,
 'ZTF17aaabavb': 5,
 'ZTF17aaabbgi': 11,
 'ZTF17aaabbjh': 6,
 'ZTF17aaabbjk': 6,
 'ZTF17aaabbjl': 6,
 'ZTF17aaabcbn': 7,
 'ZTF17aaabcnp': 4,
 'ZTF17aaabcqt': 6,
 'ZTF17aaabdmt': 5,
 'ZTF17aaabesr': 6,
 'ZTF17aaabess': 6,
 'ZTF17aaabfay': 5,
 'ZTF17aaabgdt': 2,
 'ZTF17aaabgfp': 2,
 'ZTF17aaabgfz': 2,
 'ZTF17aaabgha': 0,
 'ZTF17aaabgis': 5,
 'ZTF17aaabgjp': 3,
 'ZTF17aaabgkn': 0,
 'ZTF17aaabkwz': 6,
 'ZTF17aaabpkb': 5,
 'ZTF17aaabril': 10,
 'ZTF17aaabsps': 5,
 'ZTF17aaabtcz': 6,
 'ZTF17aaabtdt': 4,
 'ZTF17aaabtic': 6,
 'ZTF17aaabwti': 6,
 'ZTF17aaabwtj': 6,
 'ZTF17aaabwtl': 6,
 'ZTF17aaabwvd': 6,
 'ZTF17aaabzrf': 1,
 'ZTF17aaabzvl': 2,
 'ZTF17aaacaom': 5,
 'ZTF17aaaccrp': 1,
 'ZTF17aaacdos': 6,
 'ZTF17aaachjt': 3,
 'ZTF17aaachli': 3,
 'ZTF17aaaciwr': 1,
 'ZTF17aaaclph': 5,
 'ZTF17aaacmvk': 5,
 'ZTF17aaadaim': 2,
 'ZTF17aaadaow': 2,
 'ZTF17aaadapn': 3,
 'ZTF17aaadasj': 2,
 'ZTF17aaadata': 3,
 'ZTF17aaadavi': 5,
 'ZTF17aaadavp': 1,
 'ZTF17aaadayn': 6,
 'ZTF17aaadbaf': 6,
 'ZTF17aaadbvh': 6,
 'ZTF17aaaddry': 6,
 'ZTF17aaadhjr': 5,
 'ZTF17aaadjks': 8,
 'ZTF17aaadjrt': 6,
 'ZTF17aaadjul': 8,
 'ZTF17aaadjun': 6,
 'ZTF17aaadkbw': 8,
 'ZTF17aaadned': 3,
 'ZTF17aaadowa': 5,
 'ZTF17aaadoxz': 5,
 'ZTF17aaadpau': 5,
 'ZTF17aaadpcv': 4,
 'ZTF17aaadpkl': 3,
 'ZTF17aaadpqo': 4,
 'ZTF17aaadqae': 3,
 'ZTF17aaadqfm': 4,
 'ZTF17aaadqhs': 3,
 'ZTF17aaadtiy': 5,
 'ZTF17aaadtnn': 4,
 'ZTF17aaaduqv': 9,
 'ZTF17aaadvbq': 9,
 'ZTF17aaadvcd': 9,
 'ZTF17aaadvfh': 5,
 'ZTF17aaadvfi': 5,
 'ZTF17aaadxdb': 6,
 'ZTF17aaadxpb': 5,
 'ZTF17aaadxxw': 5,
 'ZTF17aaadxyb': 5,
 'ZTF17aaadxyr': 7,
 'ZTF17aaadxzc': 5,
 'ZTF17aaadxzf': 5,
 'ZTF17aaadxzy': 8,
 'ZTF17aaadxzz': 8,
 'ZTF17aaadyay': 7,
 'ZTF17aaadyca': 8,
 'ZTF17aaadyct': 7,
 'ZTF17aaadynh': 7,
 'ZTF17aaadynj': 7,
 'ZTF17aaadynk': 5,
 'ZTF17aaadynp': 7,
 'ZTF17aaadypt': 8,
 'ZTF17aaadyqb': 8,
 'ZTF17aaadyqs': 8,
 'ZTF17aaadyro': 7,
 'ZTF17aaadytr': 6,
 'ZTF17aaadyty': 6,
 'ZTF17aaadyug': 7,
 'ZTF17aaadyvo': 7,
 'ZTF17aaadywb': 7,
 'ZTF17aaadyxi': 7,
 'ZTF17aaadyxj': 8,
 'ZTF17aaadyxn': 8,
 'ZTF17aaadyyf': 5,
 'ZTF17aaadyyg': 8,
 'ZTF17aaadyzd': 6,
 'ZTF17aaadyzg': 6,
 'ZTF17aaadyzl': 5,
 'ZTF17aaadyzt': 6,
 'ZTF17aaadyzu': 6,
 'ZTF17aaadyzz': 8,
 'ZTF17aaadzaa': 8,
 'ZTF17aaadzce': 6,
 'ZTF17aaadzcj': 6,
 'ZTF17aaadzcs': 8,
 'ZTF17aaadzda': 5,
 'ZTF17aaadzef': 8,
 'ZTF17aaadzfa': 7,
 'ZTF17aaadzhb': 8,
 'ZTF17aaadzhe': 7,
 'ZTF17aaadzho': 1,
 'ZTF17aaadzjs': 8,
 'ZTF17aaadzlk': 8,
 'ZTF17aaadzlm': 8,
 'ZTF17aaadzlo': 6,
 'ZTF17aaadzlp': 6,
 'ZTF17aaadzlq': 7,
 'ZTF17aaadzpr': 8,
 'ZTF17aaadzqg': 6,
 'ZTF17aaadzqp': 7,
 'ZTF17aaadzrk': 7,
 'ZTF17aaadzrt': 6,
 'ZTF17aaaeabr': 7,
 'ZTF17aaaeaez': 6,
 'ZTF17aaaeafk': 7,
 'ZTF17aaaeagm': 7,
 'ZTF17aaaeahk': 6,
 'ZTF17aaaeaif': 6,
 'ZTF17aaaeajd': 11,
 'ZTF17aaaeall': 3,
 'ZTF17aaaealn': 10,
 'ZTF17aaaeamc': 10,
 'ZTF17aaaeamj': 2,
 'ZTF17aaaeamk': 2,
 'ZTF17aaaeanw': 8,
 'ZTF17aaaeany': 6,
 'ZTF17aaaeaoa': 6,
 'ZTF17aaaeaow': 10,
 'ZTF17aaaeapf': 6,
 'ZTF17aaaeapo': 6,
 'ZTF17aaaeaqs': 6,
 'ZTF17aaaearn': 10,
 'ZTF17aaaearu': 6,
 'ZTF17aaaeasn': 8,
 'ZTF17aaaeawl': 8,
 'ZTF17aaaeawm': 8,
 'ZTF17aaaeayf': 6,
 'ZTF17aaaeayj': 6,
 'ZTF17aaaeayl': 6,
 'ZTF17aaaeayo': 6,
 'ZTF17aaaeayp': 6,
 'ZTF17aaaeayr': 6,
 'ZTF17aaaeaza': 6,
 'ZTF17aaaebam': 6,
 'ZTF17aaaebbs': 6,
 'ZTF17aaaebcr': 6,
 'ZTF17aaaebdw': 6,
 'ZTF17aaaebeh': 6,
 'ZTF17aaaebhk': 8,
 'ZTF17aaaebkt': 10,
 'ZTF17aaaebna': 6,
 'ZTF17aaaeboq': 6,
 'ZTF17aaaebpc': 6,
 'ZTF17aaaebps': 9,
 'ZTF17aaaebwt': 6,
 'ZTF17aaaeccg': 6,
 'ZTF17aaaeceb': 7,
 'ZTF17aaaecfd': 7,
 'ZTF17aaaecfh': 7,
 'ZTF17aaaecfu': 7,
 'ZTF17aaaecgi': 7,
 'ZTF17aaaecgm': 6,
 'ZTF17aaaechg': 7,
 'ZTF17aaaecij': 8,
 'ZTF17aaaecik': 8,
 'ZTF17aaaecil': 8,
 'ZTF17aaaecin': 7,
 'ZTF17aaaecjb': 8,
 'ZTF17aaaeckh': 7,
 'ZTF17aaaeckw': 8,
 'ZTF17aaaecky': 8,
 'ZTF17aaaecla': 8,
 'ZTF17aaaeclg': 4,
 'ZTF17aaaecmi': 7,
 'ZTF17aaaecni': 7,
 'ZTF17aaaecok': 7,
 'ZTF17aaaecol': 8,
 'ZTF17aaaecor': 7,
 'ZTF17aaaecou': 7,
 'ZTF17aaaecsq': 3,
 'ZTF17aaaectt': 7,
 'ZTF17aaaectv': 7,
 'ZTF17aaaecty': 7,
 'ZTF17aaaecvb': 7,
 'ZTF17aaaecvc': 7,
 'ZTF17aaaecvj': 7,
 'ZTF17aaaecvr': 8,
 'ZTF17aaaecwh': 8,
 'ZTF17aaaecwi': 8,
 'ZTF17aaaecwl': 7,
 'ZTF17aaaecyn': 8,
 'ZTF17aaaecyw': 8,
 'ZTF17aaaeczp': 4,
 'ZTF17aaaedat': 7,
 'ZTF17aaaedaz': 8,
 'ZTF17aaaedbh': 8,
 'ZTF17aaaedde': 8,
 'ZTF17aaaedeq': 8,
 'ZTF17aaaedez': 8,
 'ZTF17aaaedfa': 8,
 'ZTF17aaaedfm': 8,
 'ZTF17aaaedfo': 7,
 'ZTF17aaaedge': 7,
 'ZTF17aaaedjr': 7,
 'ZTF17aaaedlv': 7,
 'ZTF17aaaednc': 7,
 'ZTF17aaaedoi': 6,
 'ZTF17aaaedpn': 8,
 'ZTF17aaaedpq': 8,
 'ZTF17aaaedqx': 7,
 'ZTF17aaaedrk': 6,
 'ZTF17aaaedrm': 8,
 'ZTF17aaaedtj': 8,
 'ZTF17aaaeduf': 8,
 'ZTF17aaaeduo': 6,
 'ZTF17aaaeduv': 7,
 'ZTF17aaaedvi': 7,
 'ZTF17aaaedwv': 8,
 'ZTF17aaaedyv': 7,
 'ZTF17aaaedyy': 7,
 'ZTF17aaaeeck': 8,
 'ZTF17aaaeecs': 3,
 'ZTF17aaaeeix': 7,
 'ZTF17aaaeela': 6,
 'ZTF17aaaeemj': 7,
 'ZTF17aaaeenw': 7,
 'ZTF17aaaeeny': 7,
 'ZTF17aaaeepy': 7,
 'ZTF17aaaeeqq': 8,
 'ZTF17aaaeert': 6,
 'ZTF17aaaeesi': 8,
 'ZTF17aaaeeth': 8,
 'ZTF17aaaeeto': 8,
 'ZTF17aaaegdy': 3,
 'ZTF17aaaehca': 8,
 'ZTF17aaaehgv': 7,
 'ZTF17aaaehmf': 6,
 'ZTF17aaaehmk': 9,
 'ZTF17aaaehoa': 8,
 'ZTF17aaaehqt': 7,
 'ZTF17aaaehsq': 7,
 'ZTF17aaaehsx': 6,
 'ZTF17aaaehta': 7,
 'ZTF17aaaehtj': 9,
 'ZTF17aaaehuf': 9,
 'ZTF17aaaehve': 6,
 'ZTF17aaaehvh': 9,
 'ZTF17aaaehvi': 9,
 'ZTF17aaaehvr': 9,
 'ZTF17aaaehwn': 9,
 'ZTF17aaaehwo': 9,
 'ZTF17aaaehxn': 6,
 'ZTF17aaaehxy': 6,
 'ZTF17aaaehye': 6,
 'ZTF17aaaehyw': 9,
 'ZTF17aaaehyx': 9,
 'ZTF17aaaehzb': 9,
 'ZTF17aaaehzd': 6,
 'ZTF17aaaehzz': 11,
 'ZTF17aaaeiaf': 10,
 'ZTF17aaaeiat': 9,
 'ZTF17aaaeicp': 8,
 'ZTF17aaaeido': 7,
 'ZTF17aaaeiev': 8,
 'ZTF17aaaeiex': 8,
 'ZTF17aaaeiez': 7,
 'ZTF17aaaeifc': 8,
 'ZTF17aaaeiff': 8,
 'ZTF17aaaeifx': 8,
 'ZTF17aaaeihg': 8,
 'ZTF17aaaeiis': 8,
 'ZTF17aaaeiiz': 11,
 'ZTF17aaaeijf': 8,
 'ZTF17aaaeijn': 8,
 'ZTF17aaaeikn': 7,
 'ZTF17aaaeiks': 7,
 'ZTF17aaaeikt': 7,
 'ZTF17aaaeikw': 7,
 'ZTF17aaaeiln': 7,
 'ZTF17aaaeilu': 10,
 'ZTF17aaaeipd': 6,
 'ZTF17aaaeiql': 6,
 'ZTF17aaaeirt': 7,
 'ZTF17aaaeisc': 6,
 'ZTF17aaaeisu': 5,
 'ZTF17aaaeitb': 8,
 'ZTF17aaaeivl': 7,
 'ZTF17aaaejaq': 11,
 'ZTF17aaaejcr': 8,
 'ZTF17aaaejek': 11,
 'ZTF17aaaejfe': 7,
 'ZTF17aaaejqa': 9,
 'ZTF17aaaejtu': 7,
 'ZTF17aaaejvs': 8,
 'ZTF17aaaejwm': 8,
 'ZTF17aaaekfn': 8,
 'ZTF17aaaekge': 8,
 'ZTF17aaaekkm': 7,
 'ZTF17aaaekmt': 7,
 'ZTF17aaaeknj': 7,
 'ZTF17aaaekoc': 8,
 'ZTF17aaaeksz': 7,
 'ZTF17aaaekus': 5,
 'ZTF17aaaekvi': 5,
 'ZTF17aaaekyg': 7,
 'ZTF17aaaekyn': 5,
 'ZTF17aaaekzr': 5,
 'ZTF17aaaelaa': 8,
 'ZTF17aaaelhh': 7,
 'ZTF17aaaemzh': 7,
 'ZTF17aaaeneg': 8,
 'ZTF17aaaenfh': 8,
 'ZTF17aaaenfn': 8,
 'ZTF17aaaengk': 9,
 'ZTF17aaaengo': 9,
 'ZTF17aaaenhc': 8,
 'ZTF17aaaenhs': 6,
 'ZTF17aaaenkh': 7,
 'ZTF17aaaenmh': 7,
 'ZTF17aaaenml': 8,
 'ZTF17aaaennm': 7,
 'ZTF17aaaennv': 4,
 'ZTF17aaaenok': 9,
 'ZTF17aaaenoo': 9,
 'ZTF17aaaenrr': 7,
 'ZTF17aaaentq': 5,
 'ZTF17aaaenup': 6,
 'ZTF17aaaenwn': 6,
 'ZTF17aaaenxn': 6,
 'ZTF17aaaeocl': 6,
 'ZTF17aaaeoeh': 6,
 'ZTF17aaaeoei': 6,
 'ZTF17aaaeoer': 6,
 'ZTF17aaaeoeu': 6,
 'ZTF17aaaeoew': 6,
 'ZTF17aaaeoey': 6,
 'ZTF17aaaeojh': 6,
 'ZTF17aaaeokm': 6,
 'ZTF17aaaeokw': 6,
 'ZTF17aaaeomy': 6,
 'ZTF17aaaeosv': 1,
 'ZTF17aaaeoum': 5,
 'ZTF17aaaeowa': 6,
 'ZTF17aaaeoxx': 6,
 'ZTF17aaaepdv': 6,
 'ZTF17aaaeqag': 5,
 'ZTF17aaaeqec': 3,
 'ZTF17aaaeqgy': 5,
 'ZTF17aaaeqhm': 6,
 'ZTF17aaaeqxk': 3,
 'ZTF17aaaerjh': 3,
 'ZTF17aaaesno': 9,
 'ZTF17aaaesrm': 7,
 'ZTF17aaaessu': 7,
 'ZTF17aaaesvh': 7,
 'ZTF17aaaeszr': 7,
 'ZTF17aaaeuky': 9,
 'ZTF17aaaeuoq': 5,
 'ZTF17aaaeupv': 6,
 'ZTF17aaaeupz': 9,
 'ZTF17aaaeuqg': 7,
 'ZTF17aaaeuqk': 7,
 'ZTF17aaaeurt': 6,
 'ZTF17aaaeusb': 6,
 'ZTF17aaaeutf': 6,
 'ZTF17aaaeuub': 8,
 'ZTF17aaaeuui': 6,
 'ZTF17aaaeuvb': 6,
 'ZTF17aaaeuvd': 6,
 'ZTF17aaaeuvf': 6,
 'ZTF17aaaevgx': 8,
 'ZTF17aaaeviy': 7,
 'ZTF17aaaevxe': 8,
 'ZTF17aaaevxo': 6,
 'ZTF17aaaevye': 4,
 'ZTF17aaaewaj': 2,
 'ZTF17aaaewcw': 5,
 'ZTF17aaaewjv': 5,
 'ZTF17aaaewmc': 6,
 'ZTF17aaaewmi': 5,
 'ZTF17aaaewoq': 5,
 'ZTF17aaaewpx': 5,
 'ZTF17aaaewqh': 5,
 'ZTF17aaaexha': 6,
 'ZTF17aaaexhk': 6,
 'ZTF17aaaeznw': 7,
 'ZTF17aaaezrs': 4,
 'ZTF17aaafakz': 5,
 'ZTF17aaafcun': 5,
 'ZTF17aaafffc': 4,
 'ZTF17aaafglk': 4,
 'ZTF17aaafgst': 5,
 'ZTF17aaafhcw': 5,
 'ZTF17aaafhkd': 6,
 'ZTF17aaafhpv': 6,
 'ZTF17aaafian': 6,
 'ZTF17aaafias': 6,
 'ZTF17aaafibe': 6,
 'ZTF17aaafidd': 6,
 'ZTF17aaafidt': 8,
 'ZTF17aaafidy': 8,
 'ZTF17aaafieu': 8,
 'ZTF17aaafifg': 8,
 'ZTF17aaafifi': 8,
 'ZTF17aaafihc': 8,
 'ZTF17aaafijq': 8,
 'ZTF17aaafikw': 8,
 'ZTF17aaafild': 8,
 'ZTF17aaafiml': 6,
 'ZTF17aaafios': 7,
 'ZTF17aaafipx': 6,
 'ZTF17aaafiut': 8,
 'ZTF17aaafivv': 6,
 'ZTF17aaafiwv': 7,
 'ZTF17aaafiww': 7,
 'ZTF17aaafizv': 6,
 'ZTF17aaafjai': 4,
 'ZTF17aaafjsi': 9,
 'ZTF17aaafkxc': 6,
 'ZTF17aaaflfb': 4,
 'ZTF17aaaflwj': 6,
 'ZTF17aaafnqq': 6,
 'ZTF17aaafnqr': 6,
 'ZTF17aaafoon': 4,
 'ZTF17aaafqiy': 5,
 'ZTF17aaafrmf': 5,
 'ZTF17aaaftak': 7,
 'ZTF17aaaftaw': 7,
 'ZTF17aaaftbr': 7,
 'ZTF17aaaftbz': 6,
 'ZTF17aaaftdo': 5,
 'ZTF17aaaftdz': 5,
 'ZTF17aaafuog': 6,
 'ZTF17aaafuoi': 6,
 'ZTF17aaafupm': 6,
 'ZTF17aaafupp': 6,
 'ZTF17aaafvmh': 7,
 'ZTF17aaafwnr': 3,
 'ZTF17aaafwou': 5,
 'ZTF17aaafxbb': 6,
 'ZTF17aaafxex': 6,
 'ZTF17aaafxjp': 5,
 'ZTF17aaafxks': 5,
 'ZTF17aaafxll': 6,
 'ZTF17aaafxya': 6,
 'ZTF17aaafyci': 5,
 'ZTF17aaafyfh': 5,
 'ZTF17aaafyis': 7,
 'ZTF17aaafyiy': 8,
 'ZTF17aaafynz': 8,
 'ZTF17aaafyoa': 7,
 'ZTF17aaafypx': 8,
 'ZTF17aaafyux': 8,
 'ZTF17aaafyxs': 7,
 'ZTF17aaafzma': 8,
 'ZTF17aaagabc': 3,
 'ZTF17aaagabm': 8,
 'ZTF17aaagabt': 2,
 'ZTF17aaagadx': 3,
 'ZTF17aaagapg': 4,
 'ZTF17aaagapu': 0,
 'ZTF17aaagaqa': 0,
 'ZTF17aaagari': 2,
 'ZTF17aaagath': 2,
 'ZTF17aaagatm': 2,
 'ZTF17aaagato': 2,
 'ZTF17aaagazp': 2,
 'ZTF17aaagbfr': 2,
 'ZTF17aaagbfs': 2,
 'ZTF17aaagbga': 2,
 'ZTF17aaagbjq': 4,
 'ZTF17aaagbzg': 3,
 'ZTF17aaagccm': 3,
 'ZTF17aaagcup': 2,
 'ZTF17aaageae': 4,
 'ZTF17aaaggvw': 2,
 'ZTF17aaaghhi': 7,
 'ZTF17aaaghhm': 4,
 'ZTF17aaaghhn': 7,
 'ZTF17aaagiaw': 3,
 'ZTF17aaagily': 3,
 'ZTF17aaaglec': 9,
 'ZTF17aaaglhj': 9,
 'ZTF17aaaglie': 9,
 'ZTF17aaaglug': 7,
 'ZTF17aaagmnf': 9,
 'ZTF17aaagnwk': 2,
 'ZTF17aaagnwn': 2,
 'ZTF17aaagpcv': 5,
 'ZTF17aaagpsz': 5,
 'ZTF17aaagptx': 5,
 'ZTF17aaagqfz': 5,
 'ZTF17aaagqib': 5,
 'ZTF17aaagqjv': 3,
 'ZTF17aaagqlp': 6,
 'ZTF17aaagqwm': 6,
 'ZTF17aaagqyv': 6,
 'ZTF17aaagrad': 6,
 'ZTF17aaagrbi': 6,
 'ZTF17aaagrdx': 6,
 'ZTF17aaagrgh': 6,
 'ZTF17aaagrhs': 7,
 'ZTF17aaagril': 6,
 'ZTF17aaagrir': 6,
 'ZTF17aaagrjg': 6,
 'ZTF17aaagrjh': 8,
 'ZTF17aaagrju': 7,
 'ZTF17aaagrjv': 7,
 'ZTF17aaagrkk': 6,
 'ZTF17aaagrko': 5,
 'ZTF17aaagrkx': 8,
 'ZTF17aaagrly': 7,
 'ZTF17aaagrmg': 7,
 'ZTF17aaagrmi': 6,
 'ZTF17aaagrnu': 7,
 'ZTF17aaagroa': 9,
 'ZTF17aaagroo': 7,
 'ZTF17aaagrpb': 8,
 'ZTF17aaagrpt': 8,
 'ZTF17aaagrqb': 8,
 'ZTF17aaagrqv': 2,
 'ZTF17aaagrrm': 2,
 'ZTF17aaagrrw': 7,
 'ZTF17aaagrry': 3,
 'ZTF17aaagrsl': 8,
 'ZTF17aaagrtg': 8,
 'ZTF17aaagrtk': 8,
 'ZTF17aaagrug': 2,
 'ZTF17aaagryq': 2,
 'ZTF17aaagtfy': 5,
 'ZTF17aaagthd': 4,
 'ZTF17aaagtzz': 5,
 'ZTF17aaagukn': 4,
 'ZTF17aaaguly': 1,
 'ZTF17aaaguql': 5,
 'ZTF17aaagvif': 5,
 'ZTF17aaagvih': 5,
 'ZTF17aaagvii': 5,
 'ZTF17aaagvij': 5,
 'ZTF17aaagvil': 5,
 'ZTF17aaagvim': 5,
 'ZTF17aaagvip': 5,
 'ZTF17aaagvir': 5,
 'ZTF17aaagvly': 3,
 'ZTF17aaagvnm': 3,
 'ZTF17aaagvoz': 4,
 'ZTF17aaagvsz': 4,
 'ZTF17aaagwok': 5,
 'ZTF17aaagxad': 3,
 'ZTF17aaagyfy': 2,
 'ZTF17aaagygm': 2,
 'ZTF17aaagynp': 2,
 'ZTF17aaagyop': 2,
 'ZTF17aaagyqw': 3,
 'ZTF17aaagyuc': 3,
 'ZTF17aaagzbt': 3,
 'ZTF17aaagzel': 3,
 'ZTF17aaahcwy': 4,
 'ZTF17aaahdwp': 4,
 'ZTF17aaaheem': 5,
 'ZTF17aaahefy': 3,
 'ZTF17aaahehi': 5,
 'ZTF17aaaheln': 1,
 'ZTF17aaahemg': 6,
 'ZTF17aaahepe': 5,
 'ZTF17aaahepx': 5,
 'ZTF17aaaherw': 5,
 'ZTF17aaahesa': 6,
 'ZTF17aaahevh': 1,
 'ZTF17aaahezq': 5,
 'ZTF17aaahfhn': 4,
 'ZTF17aaahfho': 6,
 'ZTF17aaahfic': 5,
 'ZTF17aaahfif': 3,
 'ZTF17aaahflv': 4,
 'ZTF17aaahgfs': 5,
 'ZTF17aaahgie': 7,
 'ZTF17aaahgsv': 6,
 'ZTF17aaahinf': 3,
 'ZTF17aaahitl': 5,
 'ZTF17aaahmid': 4,
 'ZTF17aaahmjo': 4,
 'ZTF17aaahmmm': 5,
 'ZTF17aaahmpb': 5,
 'ZTF17aaahmum': 5,
 'ZTF17aaahmxl': 6,
 'ZTF17aaahnbq': 1,
 'ZTF17aaahnsb': 5,
 'ZTF17aaahqlu': 5,
 'ZTF17aaahqnd': 5,
 'ZTF17aaahria': 3,
 'ZTF17aaahrmb': 3,
 'ZTF17aaahrrt': 2,
 'ZTF17aaahrsm': 0,
 'ZTF17aaahrta': 2,
 'ZTF17aaahrug': 1,
 'ZTF17aaahrvt': 1,
 'ZTF17aaahrwd': 0,
 'ZTF17aaahrwe': 0,
 'ZTF17aaahrwf': 2,
 'ZTF17aaahrwg': 0,
 'ZTF17aaahrwh': 0,
 'ZTF17aaahrwi': 0,
 'ZTF17aaahrwl': 2,
 'ZTF17aaahrxm': 2,
 'ZTF17aaahrya': 1,
 'ZTF17aaahryv': 3,
 'ZTF17aaahryw': 3,
 'ZTF17aaahryy': 3,
 'ZTF17aaahryz': 3,
 'ZTF17aaahrza': 3,
 'ZTF17aaahrzb': 3,
 'ZTF17aaahrzk': 3,
 'ZTF17aaahsaa': 3,
 'ZTF17aaahshu': 2,
 'ZTF17aaahsin': 2,
 'ZTF17aaahsqu': 0,
 'ZTF17aaahszr': 3,
 'ZTF17aaahtcq': 3,
 'ZTF17aaahtdr': 3,
 'ZTF17aaahtep': 3,
 'ZTF17aaahtog': 4,
 'ZTF17aaahwwy': 4,
 'ZTF17aaahxnm': 5,
 'ZTF17aaahygc': 3,
 'ZTF17aaahyrh': 7,
 'ZTF17aaahyrz': 9,
 'ZTF17aaahzsk': 6,
 'ZTF17aaahzsv': 4,
 'ZTF17aaahzut': 6,
 'ZTF17aaaiapr': 4,
 'ZTF17aaaiapz': 3,
 'ZTF17aaaiawf': 5,
 'ZTF17aaaiawg': 4,
 'ZTF17aaaibas': 6,
 'ZTF17aaaibga': 5,
 'ZTF17aaaibgb': 5,
 'ZTF17aaaidjf': 3,
 'ZTF17aaaidwk': 5,
 'ZTF17aaaidzt': 4,
 'ZTF17aaaielp': 3,
 'ZTF17aaaigdn': 5,
 'ZTF17aaaigwu': 3,
 'ZTF17aaaihcq': 4,
 'ZTF17aaaihpk': 4,
 'ZTF17aaaiidr': 4,
 'ZTF17aaaikkr': 6,
 'ZTF17aaaikuu': 6,
 'ZTF17aaaikvf': 6,
 'ZTF17aaailff': 4,
 'ZTF17aaailib': 3,
 'ZTF17aaailio': 4,
 'ZTF17aaailjd': 6,
 'ZTF17aaaillb': 3,
 'ZTF17aaailzk': 5,
 'ZTF17aaaimym': 4,
 'ZTF17aaaindr': 4,
 'ZTF17aaainmx': 5,
 'ZTF17aaainxv': 3,
 'ZTF17aaaiosv': 4,
 'ZTF17aaaipbw': 7,
 'ZTF17aaaipcy': 6,
 'ZTF17aaaipza': 7,
 'ZTF17aaaiqdu': 8,
 'ZTF17aaairbu': 9,
 'ZTF17aaairfp': 7,
 'ZTF17aaairkd': 6,
 'ZTF17aaairyo': 5,
 'ZTF17aaaitdn': 3,
 'ZTF17aaaitpz': 5,
 'ZTF17aaaitrs': 5,
 'ZTF17aaaiuwk': 7,
 'ZTF17aaaiuxn': 4,
 'ZTF17aaaivav': 4,
 'ZTF17aaaiwfl': 4,
 'ZTF17aaaiynp': 3,
 'ZTF17aaaiyrx': 4,
 'ZTF17aaaizcd': 4,
 'ZTF17aaaizfe': 4,
 'ZTF17aaaizfs': 1,
 'ZTF17aaaizfv': 4,
 'ZTF17aaaiziw': 4,
 'ZTF17aaaizxf': 5,
 'ZTF17aaajahq': 5,
 'ZTF17aaajaka': 4,
 'ZTF17aaajazz': 5,
 'ZTF17aaajbbv': 0,
 'ZTF17aaajbez': 6,
 'ZTF17aaajeks': 4,
 'ZTF17aaajeyp': 4,
 'ZTF17aaajfab': 5,
 'ZTF17aaajfbk': 4,
 'ZTF17aaajffd': 6,
 'ZTF17aaajfgr': 6,
 'ZTF17aaajfhh': 7,
 'ZTF17aaajfil': 6,
 'ZTF17aaajfxl': 4,
 'ZTF17aaajgdh': 3,
 'ZTF17aaajhgk': 0,
 'ZTF17aaajhib': 3,
 'ZTF17aaajhzf': 2,
 'ZTF17aaajigj': 5,
 'ZTF17aaajigv': 5,
 'ZTF17aaajigz': 5,
 'ZTF17aaajihk': 6,
 'ZTF17aaajijc': 7,
 'ZTF17aaajijv': 4,
 'ZTF17aaajikw': 7,
 'ZTF17aaajjee': 2,
 'ZTF17aaajjkd': 2,
 'ZTF17aaajjpk': 8,
 'ZTF17aaajjpo': 8,
 'ZTF17aaajjqm': 8,
 'ZTF17aaajjsv': 6,
 'ZTF17aaajkzm': 6,
 'ZTF17aaajlbs': 5,
 'ZTF17aaajlfr': 5,
 'ZTF17aaajlfv': 4,
 'ZTF17aaajlfw': 3,
 'ZTF17aaajllf': 2,
 'ZTF17aaajlmi': 3,
 'ZTF17aaajlnf': 3,
 'ZTF17aaajmct': 2,
 'ZTF17aaajmdq': 5,
 'ZTF17aaajmee': 3,
 'ZTF17aaajmef': 4,
 'ZTF17aaajmsc': 7,
 'ZTF17aaajmse': 7,
 'ZTF17aaajmsl': 8,
 'ZTF17aaajmth': 7,
 'ZTF17aaajmxe': 6,
 'ZTF17aaajmxw': 3,
 'ZTF17aaajnkm': 6,
 'ZTF17aaajnlh': 8,
 'ZTF17aaajnli': 7,
 'ZTF17aaajnnm': 7,
 'ZTF17aaajnnr': 8,
 'ZTF17aaajnrq': 3,
 'ZTF17aaajocp': 7,
 'ZTF17aaajoeu': 6,
 'ZTF17aaajomh': 3,
 'ZTF17aaajpfk': 3,
 'ZTF17aaajpfx': 3,
 'ZTF17aaajqjm': 4,
 'ZTF17aaajqkc': 6,
 'ZTF17aaajqkd': 6,
 'ZTF17aaajrfx': 4,
 'ZTF17aaajrob': 6,
 'ZTF17aaajrrz': 5,
 'ZTF17aaajrva': 6,
 'ZTF17aaajrwc': 6,
 'ZTF17aaajrwd': 6,
 'ZTF17aaajrwh': 6,
 'ZTF17aaajrxk': 7,
 'ZTF17aaajrxn': 7,
 'ZTF17aaajsge': 5,
 'ZTF17aaajsia': 5,
 'ZTF17aaajsnf': 5,
 'ZTF17aaajsrm': 6,
 'ZTF17aaajsrn': 6,
 'ZTF17aaajsrr': 6,
 'ZTF17aaajssv': 6,
 'ZTF17aaajsta': 6,
 'ZTF17aaajstg': 6,
 'ZTF17aaajsui': 6,
 'ZTF17aaajsum': 6,
 'ZTF17aaajsxf': 8,
 'ZTF17aaajsxy': 8,
 'ZTF17aaajsxz': 8,
 'ZTF17aaajsyg': 4,
 'ZTF17aaajtag': 6,
 'ZTF17aaajtbf': 5,
 'ZTF17aaajtbg': 7,
 'ZTF17aaajtcq': 8,
 'ZTF17aaajtfr': 7,
 'ZTF17aaajtfx': 7,
 'ZTF17aaajtgd': 7,
 'ZTF17aaajtlm': 5,
 'ZTF17aaajtva': 5,
 'ZTF17aaajtwr': 5,
 'ZTF17aaajvds': 3,
 'ZTF17aaajvzg': 6,
 'ZTF17aaajwzg': 3,
 'ZTF17aaajzet': 5,
 'ZTF17aaakame': 6,
 'ZTF17aaakbca': 6,
 'ZTF17aaakbit': 6,
 'ZTF17aaakbvl': 6,
 'ZTF17aaakccv': 4,
 'ZTF17aaakcno': 7,
 'ZTF17aaakcol': 7,
 'ZTF17aaakcou': 6,
 'ZTF17aaakebb': 3,
 'ZTF17aaakecv': 3,
 'ZTF17aaakfdt': 3,
 'ZTF17aaakfma': 5,
 'ZTF17aaakfmr': 5,
 'ZTF17aaakfoc': 5,
 'ZTF17aaakfos': 5,
 'ZTF17aaakfrg': 6,
 'ZTF17aaakguh': 6,
 'ZTF17aaakgwo': 8,
 'ZTF17aaakgyo': 8,
 'ZTF17aaakgze': 2,
 'ZTF17aaakhax': 0,
 'ZTF17aaakhba': 0,
 'ZTF17aaakhbe': 0,
 'ZTF17aaakheg': 3,
 'ZTF17aaakhep': 2,
 'ZTF17aaakheq': 2,
 'ZTF17aaakher': 2,
 'ZTF17aaakhet': 2,
 'ZTF17aaakhev': 2,
 'ZTF17aaakhfj': 3,
 'ZTF17aaakibm': 0,
 'ZTF17aaakijn': 3,
 'ZTF17aaakjph': 1,
 'ZTF17aaakjxo': 4,
 'ZTF17aaakmlx': 4,
 'ZTF17aaakobl': 4,
 'ZTF17aaakppb': 9,
 'ZTF17aaakpqk': 8,
 'ZTF17aaakpvi': 7,
 'ZTF17aaakpvs': 7,
 'ZTF17aaakquf': 5,
 'ZTF17aaakszl': 5,
 'ZTF17aaaktae': 4,
 'ZTF17aaakuex': 7,
 'ZTF17aaakuhr': 6,
 'ZTF17aaanjns': 2,
 'ZTF17aaanjpy': 4,
 'ZTF17aaanjqb': 0,
 'ZTF17aaankal': 0,
 'ZTF17aaanmso': 6,
 'ZTF17aaanmua': 6,
 'ZTF17aaannmm': 6,
 'ZTF17aaannnu': 7,
 'ZTF17aaannvv': 5,
 'ZTF17aaanohy': 6,
 'ZTF17aaanoqn': 4,
 'ZTF17aaanorm': 5,
 'ZTF17aaanpgi': 6,
 'ZTF17aaanphh': 6,
 'ZTF17aaanpjg': 1,
 'ZTF17aaanpks': 3,
 'ZTF17aaanplz': 3,
 'ZTF17aaanpmc': 3,
 'ZTF17aaanppi': 2,
 'ZTF17aaanppz': 3,
 'ZTF17aaanpqk': 3,
 'ZTF17aaanpua': 3,
 'ZTF17aaanpyr': 3,
 'ZTF17aaanqai': 3,
 'ZTF17aaanqds': 3,
 'ZTF17aaanqdt': 3,
 'ZTF17aaanqgn': 3,
 'ZTF17aaanqyh': 4,
 'ZTF17aaanrbr': 1,
 'ZTF17aaanrgi': 5,
 'ZTF17aaanrgk': 5,
 'ZTF17aaanrhg': 5,
 'ZTF17aaanrhv': 5,
 'ZTF17aaanrhy': 5,
 'ZTF17aaanrib': 5,
 'ZTF17aaanrid': 2,
 'ZTF17aaanrif': 5,
 'ZTF17aaanrig': 5,
 'ZTF17aaanrim': 5,
 'ZTF17aaanrip': 5,
 'ZTF17aaanrir': 5,
 'ZTF17aaanrit': 5,
 'ZTF17aaanriu': 5,
 'ZTF17aaanrvi': 3,
 'ZTF17aaantax': 4,
 'ZTF17aaantxj': 5,
 'ZTF17aaanwxd': 3,
 'ZTF17aaanxvn': 2,
 'ZTF17aaanyhq': 5,
 'ZTF17aaanysn': 3,
 'ZTF17aaanyug': 0,
 'ZTF17aaanyvc': 0,
 'ZTF17aaanzaz': 5,
 'ZTF17aaanzen': 4,
 'ZTF17aaaoasj': 6,
 'ZTF17aaaobmx': 5,
 'ZTF17aaaobsl': 6,
 'ZTF17aaaobyl': 4,
 'ZTF17aaaocpq': 1,
 'ZTF17aaaocqt': 5,
 'ZTF17aaaocsn': 4,
 'ZTF17aaaohet': 5,
 'ZTF17aaaohjq': 4,
 'ZTF17aaaoidu': 5,
 'ZTF17aaaoinp': 6,
 'ZTF17aaaoipm': 5,
 'ZTF17aaaoipp': 5,
 'ZTF17aaaoirx': 5,
 'ZTF17aaaoite': 6,
 'ZTF17aaaoivi': 6,
 'ZTF17aaaoixm': 5,
 'ZTF17aaaoixt': 2,
 'ZTF17aaaojbj': 3,
 'ZTF17aaaojbm': 6,
 'ZTF17aaaojjk': 3,
 'ZTF17aaaojkm': 4,
 'ZTF17aaaojkq': 4,

In [ ]:
final_windows_merged_df

                                                      sigma_flux_diff_ujy
oid          window_id
ZTF17aaaaabj 0          [8.440242655407886, 9.70802999032586, 20.01827...  \
             1          [4.335927383739846, 2.337136437970241, 2.61231...
             2          [3.3180606229102576, 3.4208377390652815, 3.416...
             3          [4.021680458844159, 4.18601374614786, 4.365849...
             4          [7.990314418768771, 8.825867966180457, 10.4053...
...                                                                   ...
ZTF23aboxuyi 0          [4.789168652528449, 6.6113980531103085, 4.0210...
             1          [10.31127100662421, 7.095175466434133, 4.76234...
             2          [8.438503543741724, 9.441484804282839, 5.70083...
ZTF23abpbdyh 0          [5.791383450140314, 3.544662523295157, 2.92826...
ZTF23abpbuha 0          [13.62036221217015, 14.48718316429837, 11.4438...

                                                                 detected
oid          window_id
ZTF17aaaaabj 0          [True, True, True, False, True, True, True, Tr...  \
             1          [True, True, True, True, True, True, True, Tru...
             2          [True, True, True, True, True, True, True, Tru...
             3          [False, False, False, True, True, True, True, ...
             4          [True, True, True, True, True, True, True, Tru...
...                                                                   ...
ZTF23aboxuyi 0          [False, False, False, False, False, False, Fal...
             1          [False, False, False, False, False, False, Tru...
             2          [False, False, False, False, False, False, Fal...
ZTF23abpbdyh 0          [False, False, False, False, False, False, Fal...
ZTF23abpbuha 0                      [True, False, True, True, True, True]

                                                            flux_diff_ujy
oid          window_id
ZTF17aaaaabj 0          [-249.57181969652103, 52.815739767359396, -253...  \
             1          [318.88202860232195, -230.68964424237782, -148...
             2          [-343.69137256798797, -341.49161921565184, -35...
             3          [19.587287226180354, 4.68433612312114, 0.74238...
             4          [196.79623824291224, 301.52910950582645, -288....
...                                                                   ...
ZTF23aboxuyi 0          [1.1547001816474889, -0.84922994538376, 0.5157...
             1          [22.27578010361939, 27.833914276248418, 15.723...
             2          [13.20777222894057, 17.15569121649437, 12.1412...
ZTF23abpbdyh 0          [6.666708298405723, 3.4420276517688113, 3.3954...
ZTF23abpbuha 0          [169.48633315872158, 32.28439269439875, 157.16...

                                                                      fid
oid          window_id
ZTF17aaaaabj 0          [1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ...  \
             1          [2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ...
             2          [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
             3          [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
             4          [1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
...                                                                   ...
ZTF23aboxuyi 0          [1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, ...
             1          [1, 2, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3, 2, 1, ...
             2          [2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, ...
ZTF23abpbdyh 0                             [2, 2, 1, 2, 1, 2, 1, 1, 1, 2]
ZTF23abpbuha 0                                         [2, 1, 2, 1, 2, 2]

                                                                      mjd
oid          window_id
ZTF17aaaaabj 0          [58206.16430559987, 58231.14488429995, 58234.1...  \
             1          [58491.22325230017, 58493.221169000026, 58493....
             2          [58806.42067130003, 58806.421134300064, 58806....
             3          [59043.470949099865, 59043.47599539999, 59043....
             4          [59294.158067100216, 59294.19618060021, 59296....
...                                                                   ...
ZTF23aboxuyi 0          [58872.165138899814, 58875.09256940009, 58875....
             1          [59418.46142360009, 59422.43584490009, 59426.4...
             2          [59803.41695600003, 59803.45730319992, 59808.4...
ZTF23abpbdyh 0          [60236.48218750022, 60238.51758099999, 60242.4...
ZTF23abpbuha 0          [60248.48346060002, 60248.50972220022, 60251.4...

                       alerceclass
oid          window_id
ZTF17aaaaabj 0                RRLc
             1                RRLc
             2                RRLc
             3                RRLc
             4                RRLc
...                            ...
ZTF23aboxuyi 0                 QSO
             1                 QSO
             2                 QSO
ZTF23abpbdyh 0             CV/Nova
ZTF23abpbuha 0                SNII

[253017 rows x 6 columns]

In [57]:
def open_partitions(partitions, dict_cols):
    mapping_to_int = {key: idx for idx, key in enumerate(partitions[dict_cols['class']].unique())}

    def apply_mapping(label_str):
        return mapping_to_int[label_str]

    partitions['label_int'] = partitions.apply(lambda x: apply_mapping(x[dict_cols['class']]), axis=1)
    return partitions, mapping_to_int

df_partitions = pd.read_parquet('./data/datasets/ZTF_ff/partitions/v3/partitions.parquet')
df_partitions

                oid     alerceclass     partition
index
23577  ZTF18adldhip             AGN          test
32093  ZTF19aasbgeb             QSO          test
17103  ZTF18aayfbqd              EA          test
6117   ZTF19ablyzbl             QSO          test
33717  ZTF18actabfv             YSO          test
...             ...             ...           ...
41704  ZTF19acokmuo             AGN  validation_4
41708  ZTF18abxoxih          Blazar  validation_4
41716  ZTF18adbhpsf          Blazar  validation_4
41719  ZTF21aamkwra  Periodic-Other  validation_4
41726  ZTF23aaqniyk            SNII  validation_4

[175256 rows x 3 columns]

In [58]:
pp = final_windows_merged_df.reset_index()
pp.head()

,oid,window_id,detected,mjd,sigma_flux_diff_ujy,flux_diff_ujy,fid,alerceclass
0,ZTF17aaaaabj,0,"[True, True, True, False, True, True, True, Tr...","[58206.16430559987, 58231.14488429995, 58234.1...","[8.440242655407886, 9.70802999032586, 20.01827...","[-249.57181969652103, 52.815739767359396, -253...","[1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ...",RRLc
1,ZTF17aaaaabj,1,"[True, True, True, True, True, True, True, Tru...","[58491.22325230017, 58493.221169000026, 58493....","[4.335927383739846, 2.337136437970241, 2.61231...","[318.88202860232195, -230.68964424237782, -148...","[2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ...",RRLc
2,ZTF17aaaaabj,2,"[True, True, True, True, True, True, True, Tru...","[58806.42067130003, 58806.421134300064, 58806....","[3.3180606229102576, 3.4208377390652815, 3.416...","[-343.69137256798797, -341.49161921565184, -35...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",RRLc
3,ZTF17aaaaabj,3,"[False, False, False, True, True, True, True, ...","[59043.470949099865, 59043.47599539999, 59043....","[4.021680458844159, 4.18601374614786, 4.365849...","[19.587287226180354, 4.68433612312114, 0.74238...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",RRLc
4,ZTF17aaaaabj,4,"[True, True, True, True, True, True, True, Tru...","[59294.158067100216, 59294.19618060021, 59296....","[7.990314418768771, 8.825867966180457, 10.4053...","[196.79623824291224, 301.52910950582645, -288....","[1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",RRLc

In [ ]:
name_cols = ['oid', 'window_id', 'alerceclass', 'partition']

test_partition = df_partitions[df_partitions['partition'] == 'test']

partitions = []
aa = pd.merge(test_partition, pp.drop(['alerceclass'], axis=1), on='oid', how='outer').dropna()[name_cols]
partitions.append(aa)
partitions[0]

                oid  window_id alerceclass partition
0      ZTF18adldhip          0         AGN      test
1      ZTF18adldhip          1         AGN      test
2      ZTF18adldhip          2         AGN      test
3      ZTF18adldhip          3         AGN      test
4      ZTF19aasbgeb          0         QSO      test
...             ...        ...         ...       ...
50496  ZTF17aabpjme          6       RRLab      test
50497  ZTF17aabpjme          7       RRLab      test
50498  ZTF18acrwlnr          0         YSO      test
50499  ZTF18acrwlnr          1         YSO      test
50500  ZTF18acrwlnr          2         YSO      test

[50501 rows x 4 columns]

In [ ]:
for fold in range(5):
    print('We are expanding the number of windows per light curve in fold {}...'.format(fold))
    this_partitions = df_partitions[(df_partitions['partition'] == 'training_%d' %  fold) | \
                                    (df_partitions['partition'] == 'validation_%d' % fold)]
    
    aa = pd.merge(this_partitions, pp.drop(['alerceclass'], axis=1), on='oid', how='outer').dropna()[name_cols]

    partitions.append(aa)

We are expanding the number of windows per light curve in fold 0...
We are expanding the number of windows per light curve in fold 1...
We are expanding the number of windows per light curve in fold 2...
We are expanding the number of windows per light curve in fold 3...
We are expanding the number of windows per light curve in fold 4...

In [ ]:
aa

                 oid  window_id     alerceclass     partition
0       ZTF21acasmne          0         CV/Nova    training_4
1       ZTF21acasmne          1         CV/Nova    training_4
2       ZTF21acasmne          2         CV/Nova    training_4
3       ZTF21acasmne          3         CV/Nova    training_4
4       ZTF17aabhkmn          0             YSO    training_4
...              ...        ...             ...           ...
202304  ZTF18adbhpsf          2          Blazar  validation_4
202305  ZTF18adbhpsf          3          Blazar  validation_4
202306  ZTF21aamkwra          0  Periodic-Other  validation_4
202307  ZTF21aamkwra          1  Periodic-Other  validation_4
202308  ZTF23aaqniyk          0            SNII  validation_4

[202309 rows x 4 columns]

In [ ]:
aa.oid.nunique()

33382

In [ ]:
def select_random_window_id(group):
    return group.sample(n=1)

# Agrupamos por 'oid' y aplicamos la función
random_window_ids = aa.groupby('oid').apply(select_random_window_id).reset_index(drop=True)
random_window_ids

                oid  window_id alerceclass     partition
0      ZTF17aaaaabj          2        RRLc  validation_4
1      ZTF17aaaaaej          3        RRLc    training_4
2      ZTF17aaaaajg          0        RRLc  validation_4
3      ZTF17aaaaavq         10         LPV    training_4
4      ZTF17aaaaaya          1       RRLab  validation_4
...             ...        ...         ...           ...
33377  ZTF23abobwsd          0        SNII    training_4
33378  ZTF23abofpay          0       SNIbc    training_4
33379  ZTF23aboxuyi          1         QSO    training_4
33380  ZTF23abpbdyh          0     CV/Nova    training_4
33381  ZTF23abpbuha          0        SNII    training_4

[33382 rows x 4 columns]

In [ ]:
aa

                 oid  window_id     alerceclass     partition
0       ZTF21acasmne          0         CV/Nova    training_4
1       ZTF21acasmne          1         CV/Nova    training_4
2       ZTF21acasmne          2         CV/Nova    training_4
3       ZTF21acasmne          3         CV/Nova    training_4
4       ZTF17aabhkmn          0             YSO    training_4
...              ...        ...             ...           ...
202304  ZTF18adbhpsf          2          Blazar  validation_4
202305  ZTF18adbhpsf          3          Blazar  validation_4
202306  ZTF21aamkwra          0  Periodic-Other  validation_4
202307  ZTF21aamkwra          1  Periodic-Other  validation_4
202308  ZTF23aaqniyk          0            SNII  validation_4

[202309 rows x 4 columns]

In [ ]:
partitions[5]

                 oid  window_id     alerceclass     partition
0       ZTF21acasmne          0         CV/Nova    training_4
1       ZTF21acasmne          1         CV/Nova    training_4
2       ZTF21acasmne          2         CV/Nova    training_4
3       ZTF21acasmne          3         CV/Nova    training_4
4       ZTF17aabhkmn          0             YSO    training_4
...              ...        ...             ...           ...
202304  ZTF18adbhpsf          2          Blazar  validation_4
202305  ZTF18adbhpsf          3          Blazar  validation_4
202306  ZTF21aamkwra          0  Periodic-Other  validation_4
202307  ZTF21aamkwra          1  Periodic-Other  validation_4
202308  ZTF23aaqniyk          0            SNII  validation_4

[202309 rows x 4 columns]

In [ ]:
filtered_0 = pd.merge(partitions[1], random_window_ids[['oid', 'window_id']], on=['oid', 'window_id'])
filtered_0

                oid  window_id alerceclass     partition
0      ZTF21acasmne          0     CV/Nova    training_0
1      ZTF17aabhkmn          3         YSO    training_0
2      ZTF18aatxhtl          5         QSO    training_0
3      ZTF18aaadfyl          2       RSCVn    training_0
4      ZTF19aapocaj          0         QSO    training_0
...             ...        ...         ...           ...
33377  ZTF18aazngol          1         LPV  validation_0
33378  ZTF18aaxjkjm          6       EB/EW  validation_0
33379  ZTF18adruaae          3         YSO  validation_0
33380  ZTF18acacrgm          5       EB/EW  validation_0
33381  ZTF18aajbozk          6        DSCT  validation_0

[33382 rows x 4 columns]

In [ ]:
pp.drop(['alerceclass'], axis=1)

,oid,window_id,detected,mjd,fid,flux_diff_ujy,sigma_flux_diff_ujy
0,ZTF17aaaaabj,0,"[True, True, True, False, True, True, True, Tr...","[58206.16430559987, 58231.14488429995, 58234.1...","[1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ...","[-249.57181969652103, 52.815739767359396, -253...","[8.440242655407886, 9.70802999032586, 20.01827..."
1,ZTF17aaaaabj,1,"[True, True, True, True, True, True, True, Tru...","[58491.22325230017, 58493.221169000026, 58493....","[2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ...","[318.88202860232195, -230.68964424237782, -148...","[4.335927383739846, 2.337136437970241, 2.61231..."
2,ZTF17aaaaabj,2,"[True, True, True, True, True, True, True, Tru...","[58806.42067130003, 58806.421134300064, 58806....","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[-343.69137256798797, -341.49161921565184, -35...","[3.3180606229102576, 3.4208377390652815, 3.416..."
3,ZTF17aaaaabj,3,"[False, False, False, True, True, True, True, ...","[59043.470949099865, 59043.47599539999, 59043....","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[19.587287226180354, 4.68433612312114, 0.74238...","[4.021680458844159, 4.18601374614786, 4.365849..."
4,ZTF17aaaaabj,4,"[True, True, True, True, True, True, True, Tru...","[59294.158067100216, 59294.19618060021, 59296....","[1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[196.79623824291224, 301.52910950582645, -288....","[7.990314418768771, 8.825867966180457, 10.4053..."
...,...,...,...,...,...,...,...
253012,ZTF23aboxuyi,0,"[False, False, False, False, False, False, Fal...","[58872.165138899814, 58875.09256940009, 58875....","[1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, ...","[1.1547001816474889, -0.84922994538376, 0.5157...","[4.789168652528449, 6.6113980531103085, 4.0210..."
253013,ZTF23aboxuyi,1,"[False, False, False, False, False, False, Tru...","[59418.46142360009, 59422.43584490009, 59426.4...","[1, 2, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3, 2, 1, ...","[22.27578010361939, 27.833914276248418, 15.723...","[10.31127100662421, 7.095175466434133, 4.76234..."
253014,ZTF23aboxuyi,2,"[False, False, False, False, False, False, Fal...","[59803.41695600003, 59803.45730319992, 59808.4...","[2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, ...","[13.20777222894057, 17.15569121649437, 12.1412...","[8.438503543741724, 9.441484804282839, 5.70083..."
253015,ZTF23abpbdyh,0,"[False, False, False, False, False, False, Fal...","[60236.48218750022, 60238.51758099999, 60242.4...","[2, 2, 1, 2, 1, 2, 1, 1, 1, 2]","[6.666708298405723, 3.4420276517688113, 3.3954...","[5.791383450140314, 3.544662523295157, 2.92826..."
253016,ZTF23abpbuha,0,"[True, False, True, True, True, True]","[60248.48346060002, 60248.50972220022, 60251.4...","[2, 1, 2, 1, 2, 2]","[169.48633315872158, 32.28439269439875, 157.16...","[13.62036221217015, 14.48718316429837, 11.4438..."

In [ ]:
df = pd.concat(partitions)
df

                 oid  window_id     alerceclass     partition
0       ZTF18adldhip          0             AGN          test
1       ZTF18adldhip          1             AGN          test
2       ZTF18adldhip          2             AGN          test
3       ZTF18adldhip          3             AGN          test
4       ZTF19aasbgeb          0             QSO          test
...              ...        ...             ...           ...
202304  ZTF18adbhpsf          2          Blazar  validation_4
202305  ZTF18adbhpsf          3          Blazar  validation_4
202306  ZTF21aamkwra          0  Periodic-Other  validation_4
202307  ZTF21aamkwra          1  Periodic-Other  validation_4
202308  ZTF23aaqniyk          0            SNII  validation_4

[1062046 rows x 4 columns]

In [ ]:
df['oid'] = df['oid'].astype(str) + '_' + df['window_id'].astype(str)
df = df.drop(['window_id'], axis=1)

In [ ]:
df

                   oid     alerceclass     partition
0       ZTF18adldhip_0             AGN          test
1       ZTF18adldhip_1             AGN          test
2       ZTF18adldhip_2             AGN          test
3       ZTF18adldhip_3             AGN          test
4       ZTF19aasbgeb_0             QSO          test
...                ...             ...           ...
202304  ZTF18adbhpsf_2          Blazar  validation_4
202305  ZTF18adbhpsf_3          Blazar  validation_4
202306  ZTF21aamkwra_0  Periodic-Other  validation_4
202307  ZTF21aamkwra_1  Periodic-Other  validation_4
202308  ZTF23aaqniyk_0            SNII  validation_4

[1062046 rows x 3 columns]

In [ ]:
import copy

def expands_ids(partitions_final, snid, df_partition, dict_snid_windows, dict_cols):
    aux_snid = copy.copy(snid)
    df_aux = df_partition[df_partition[dict_cols['oid']] == snid]
    num_windows = dict_snid_windows[snid] 
    
    for i in range(num_windows+1):
        df_aux.loc[df_aux[dict_cols['oid']] == aux_snid, dict_cols['oid']] = '{}_{}'.format(snid, i)
        partitions_final.append(df_aux.copy())
        aux_snid = '{}_{}'.format(snid, i)

partitions_final = []

ids_test = test_partition[dict_cols['oid']].values
for snid in ids_test:
    expands_ids(partitions_final, snid, test_partition, df_a[1], dict_cols)

/tmp/ipykernel_1918420/2483919658.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_aux.loc[df_aux[dict_cols['oid']] == aux_snid, dict_cols['oid']] = '{}_{}'.format(snid, i)

In [ ]:
partitions_final[0]

                  oid alerceclass partition
index
23577  ZTF18adldhip_0         AGN      test

In [ ]:
# Merge between light curves and partitions

def ordered_partitions(df_lc, partitions, fold, dict_cols):
    this_partition = partitions[(partitions['partition'] == 'training_%d' %  fold) | \
                                (partitions['partition'] == 'validation_%d' % fold) | \
                                (partitions['partition'] == 'test')]
    this_partition       = this_partition.set_index(dict_cols['oid'])
    this_partition_final = this_partition.filter(items=df_lc.index, axis=0)
    this_partition_final['unique_id'] = np.arange(len(this_partition_final))
    this_partition_final = this_partition_final.reset_index().rename(columns={'index': dict_cols['oid']})
    this_partition_final = this_partition_final.set_index('unique_id')
    return this_partition_final

num_folds = 5
all_partitions = {}
for fold in range(num_folds):
    all_partitions['fold_%s' % fold] = ordered_partitions(df_lcs, 
                                                          df_partitions, 
                                                          fold,
                                                          dict_cols)

In [ ]:
final_windows_merged_df

                                                      sigma_flux_diff_ujy
oid          window_id
ZTF17aaaaabj 0          [8.440242655407886, 9.70802999032586, 20.01827...  \
             1          [4.335927383739846, 2.337136437970241, 2.61231...
             2          [3.3180606229102576, 3.4208377390652815, 3.416...
             3          [4.021680458844159, 4.18601374614786, 4.365849...
             4          [7.990314418768771, 8.825867966180457, 10.4053...
...                                                                   ...
ZTF23aboxuyi 0          [4.789168652528449, 6.6113980531103085, 4.0210...
             1          [10.31127100662421, 7.095175466434133, 4.76234...
             2          [8.438503543741724, 9.441484804282839, 5.70083...
ZTF23abpbdyh 0          [5.791383450140314, 3.544662523295157, 2.92826...
ZTF23abpbuha 0          [13.62036221217015, 14.48718316429837, 11.4438...

                                                                 detected
oid          window_id
ZTF17aaaaabj 0          [True, True, True, False, True, True, True, Tr...  \
             1          [True, True, True, True, True, True, True, Tru...
             2          [True, True, True, True, True, True, True, Tru...
             3          [False, False, False, True, True, True, True, ...
             4          [True, True, True, True, True, True, True, Tru...
...                                                                   ...
ZTF23aboxuyi 0          [False, False, False, False, False, False, Fal...
             1          [False, False, False, False, False, False, Tru...
             2          [False, False, False, False, False, False, Fal...
ZTF23abpbdyh 0          [False, False, False, False, False, False, Fal...
ZTF23abpbuha 0                      [True, False, True, True, True, True]

                                                            flux_diff_ujy
oid          window_id
ZTF17aaaaabj 0          [-249.57181969652103, 52.815739767359396, -253...  \
             1          [318.88202860232195, -230.68964424237782, -148...
             2          [-343.69137256798797, -341.49161921565184, -35...
             3          [19.587287226180354, 4.68433612312114, 0.74238...
             4          [196.79623824291224, 301.52910950582645, -288....
...                                                                   ...
ZTF23aboxuyi 0          [1.1547001816474889, -0.84922994538376, 0.5157...
             1          [22.27578010361939, 27.833914276248418, 15.723...
             2          [13.20777222894057, 17.15569121649437, 12.1412...
ZTF23abpbdyh 0          [6.666708298405723, 3.4420276517688113, 3.3954...
ZTF23abpbuha 0          [169.48633315872158, 32.28439269439875, 157.16...

                                                                      fid
oid          window_id
ZTF17aaaaabj 0          [1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ...  \
             1          [2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ...
             2          [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
             3          [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
             4          [1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...
...                                                                   ...
ZTF23aboxuyi 0          [1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, ...
             1          [1, 2, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3, 2, 1, ...
             2          [2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, ...
ZTF23abpbdyh 0                             [2, 2, 1, 2, 1, 2, 1, 1, 1, 2]
ZTF23abpbuha 0                                         [2, 1, 2, 1, 2, 2]

                                                                      mjd
oid          window_id
ZTF17aaaaabj 0          [58206.16430559987, 58231.14488429995, 58234.1...  \
             1          [58491.22325230017, 58493.221169000026, 58493....
             2          [58806.42067130003, 58806.421134300064, 58806....
             3          [59043.470949099865, 59043.47599539999, 59043....
             4          [59294.158067100216, 59294.19618060021, 59296....
...                                                                   ...
ZTF23aboxuyi 0          [58872.165138899814, 58875.09256940009, 58875....
             1          [59418.46142360009, 59422.43584490009, 59426.4...
             2          [59803.41695600003, 59803.45730319992, 59808.4...
ZTF23abpbdyh 0          [60236.48218750022, 60238.51758099999, 60242.4...
ZTF23abpbuha 0          [60248.48346060002, 60248.50972220022, 60251.4...

                       alerceclass
oid          window_id
ZTF17aaaaabj 0                RRLc
             1                RRLc
             2                RRLc
             3                RRLc
             4                RRLc
...                            ...
ZTF23aboxuyi 0                 QSO
             1                 QSO
             2                 QSO
ZTF23abpbdyh 0             CV/Nova
ZTF23abpbuha 0                SNII

[253017 rows x 6 columns]

In [59]:
df_lc = pp.drop(['alerceclass'], axis=1)
print(df_lc.shape)
df_lc.head()

(253017, 7)

,oid,window_id,detected,mjd,sigma_flux_diff_ujy,flux_diff_ujy,fid
0,ZTF17aaaaabj,0,"[True, True, True, False, True, True, True, Tr...","[58206.16430559987, 58231.14488429995, 58234.1...","[8.440242655407886, 9.70802999032586, 20.01827...","[-249.57181969652103, 52.815739767359396, -253...","[1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ..."
1,ZTF17aaaaabj,1,"[True, True, True, True, True, True, True, Tru...","[58491.22325230017, 58493.221169000026, 58493....","[4.335927383739846, 2.337136437970241, 2.61231...","[318.88202860232195, -230.68964424237782, -148...","[2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ..."
2,ZTF17aaaaabj,2,"[True, True, True, True, True, True, True, Tru...","[58806.42067130003, 58806.421134300064, 58806....","[3.3180606229102576, 3.4208377390652815, 3.416...","[-343.69137256798797, -341.49161921565184, -35...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
3,ZTF17aaaaabj,3,"[False, False, False, True, True, True, True, ...","[59043.470949099865, 59043.47599539999, 59043....","[4.021680458844159, 4.18601374614786, 4.365849...","[19.587287226180354, 4.68433612312114, 0.74238...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
4,ZTF17aaaaabj,4,"[True, True, True, True, True, True, True, Tru...","[59294.158067100216, 59294.19618060021, 59296....","[7.990314418768771, 8.825867966180457, 10.4053...","[196.79623824291224, 301.52910950582645, -288....","[1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."

In [60]:
dict_info = {'undersampling_windows': { # Solo funciona con type_windows: windows
            'apply': True,
            'same_windows_by_folds': True,
            'keep_classes': [
                "SNIbc",
                "SNIIn",
                "SLSN",
                "TDE",
                "SNIIb",
                "Microlensing",
            ]
        }
}

name_cols = ['oid', 'window_id', 'alerceclass', 'partition']

test_partition = df_partitions[df_partitions['partition'] == 'test']

partitions_final = []
df_partition_expand = pd.merge(test_partition, df_lc, on='oid', how='outer').dropna()[name_cols]
partitions_final.append(df_partition_expand)


for fold in range(5):
    print('We are expanding the number of windows per light curve in fold {}...'.format(fold))
    this_partitions = df_partitions[(df_partitions['partition'] == 'training_%d' %  fold) | \
                                    (df_partitions['partition'] == 'validation_%d' % fold)]
    
    df_partition_expand = pd.merge(this_partitions, df_lc, on='oid', how='outer').dropna()[name_cols]
    

    if dict_info['undersampling_windows']['apply']:
        if dict_info['undersampling_windows']['same_windows_by_folds']: 
            if fold == 0:
                df_keep_windows = df_partition_expand[
                    df_partition_expand['alerceclass'].isin(dict_info['undersampling_windows']['keep_classes'])
                    ]
                df_partition_expand = df_partition_expand.loc[~df_partition_expand.index.isin(df_keep_windows.index)]

                df_random_window_ids = df_partition_expand.groupby('oid').apply(lambda group: group.sample(n=1)).reset_index(drop=True)
                df_final_windows = pd.concat([df_keep_windows, df_random_window_ids])
                df_aux = df_final_windows.copy()

            else:
                df_final_windows = pd.merge(
                    df_partition_expand, 
                    df_aux[['oid', 'window_id']], 
                    on=['oid', 'window_id']
                )

        else:
            df_keep_windows = df_partition_expand[
                df_partition_expand['alerceclass'].isin(dict_info['undersampling_windows']['keep_classes'])
                ]
            df_partition_expand = df_partition_expand.loc[~df_partition_expand.index.isin(df_keep_windows.index)]

            df_random_window_ids = df_partition_expand.groupby('oid').apply(lambda group: group.sample(n=1)).reset_index(drop=True)
            df_final_windows = pd.concat([df_keep_windows, df_random_window_ids])

        partitions_final.append(df_final_windows)

    else:
        partitions_final.append(df_partition_expand)

We are expanding the number of windows per light curve in fold 0...
We are expanding the number of windows per light curve in fold 1...
We are expanding the number of windows per light curve in fold 2...
We are expanding the number of windows per light curve in fold 3...
We are expanding the number of windows per light curve in fold 4...

In [61]:
df_partitions = pd.concat(partitions_final)
df_partitions

                oid  window_id     alerceclass     partition
0      ZTF18adldhip          0             AGN          test
1      ZTF18adldhip          1             AGN          test
2      ZTF18adldhip          2             AGN          test
3      ZTF18adldhip          3             AGN          test
4      ZTF19aasbgeb          0             QSO          test
...             ...        ...             ...           ...
35972  ZTF19acokmuo          7             AGN  validation_4
35973  ZTF18abxoxih          1          Blazar  validation_4
35974  ZTF18adbhpsf          1          Blazar  validation_4
35975  ZTF21aamkwra          0  Periodic-Other  validation_4
35976  ZTF23aaqniyk          0            SNII  validation_4

[230386 rows x 4 columns]

In [62]:
df_partitions['oid'] = df_partitions['oid'].astype(str) + '_' + df_partitions['window_id'].astype(str)
df_partitions = df_partitions.drop(columns=['window_id'])
df_partitions

                  oid     alerceclass     partition
0      ZTF18adldhip_0             AGN          test
1      ZTF18adldhip_1             AGN          test
2      ZTF18adldhip_2             AGN          test
3      ZTF18adldhip_3             AGN          test
4      ZTF19aasbgeb_0             QSO          test
...               ...             ...           ...
35972  ZTF19acokmuo_7             AGN  validation_4
35973  ZTF18abxoxih_1          Blazar  validation_4
35974  ZTF18adbhpsf_1          Blazar  validation_4
35975  ZTF21aamkwra_0  Periodic-Other  validation_4
35976  ZTF23aaqniyk_0            SNII  validation_4

[230386 rows x 3 columns]

In [63]:
df_lc['oid'] = df_lc['oid'].astype(str) + '_' + df_lc['window_id'].astype(str)
df_lc = df_lc.drop(columns=['window_id'])
df_lc

,oid,detected,mjd,sigma_flux_diff_ujy,flux_diff_ujy,fid
0,ZTF17aaaaabj_0,"[True, True, True, False, True, True, True, Tr...","[58206.16430559987, 58231.14488429995, 58234.1...","[8.440242655407886, 9.70802999032586, 20.01827...","[-249.57181969652103, 52.815739767359396, -253...","[1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ..."
1,ZTF17aaaaabj_1,"[True, True, True, True, True, True, True, Tru...","[58491.22325230017, 58493.221169000026, 58493....","[4.335927383739846, 2.337136437970241, 2.61231...","[318.88202860232195, -230.68964424237782, -148...","[2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ..."
2,ZTF17aaaaabj_2,"[True, True, True, True, True, True, True, Tru...","[58806.42067130003, 58806.421134300064, 58806....","[3.3180606229102576, 3.4208377390652815, 3.416...","[-343.69137256798797, -341.49161921565184, -35...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
3,ZTF17aaaaabj_3,"[False, False, False, True, True, True, True, ...","[59043.470949099865, 59043.47599539999, 59043....","[4.021680458844159, 4.18601374614786, 4.365849...","[19.587287226180354, 4.68433612312114, 0.74238...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
4,ZTF17aaaaabj_4,"[True, True, True, True, True, True, True, Tru...","[59294.158067100216, 59294.19618060021, 59296....","[7.990314418768771, 8.825867966180457, 10.4053...","[196.79623824291224, 301.52910950582645, -288....","[1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
...,...,...,...,...,...,...
253012,ZTF23aboxuyi_0,"[False, False, False, False, False, False, Fal...","[58872.165138899814, 58875.09256940009, 58875....","[4.789168652528449, 6.6113980531103085, 4.0210...","[1.1547001816474889, -0.84922994538376, 0.5157...","[1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, ..."
253013,ZTF23aboxuyi_1,"[False, False, False, False, False, False, Tru...","[59418.46142360009, 59422.43584490009, 59426.4...","[10.31127100662421, 7.095175466434133, 4.76234...","[22.27578010361939, 27.833914276248418, 15.723...","[1, 2, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3, 2, 1, ..."
253014,ZTF23aboxuyi_2,"[False, False, False, False, False, False, Fal...","[59803.41695600003, 59803.45730319992, 59808.4...","[8.438503543741724, 9.441484804282839, 5.70083...","[13.20777222894057, 17.15569121649437, 12.1412...","[2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, ..."
253015,ZTF23abpbdyh_0,"[False, False, False, False, False, False, Fal...","[60236.48218750022, 60238.51758099999, 60242.4...","[5.791383450140314, 3.544662523295157, 2.92826...","[6.666708298405723, 3.4420276517688113, 3.3954...","[2, 2, 1, 2, 1, 2, 1, 1, 1, 2]"
253016,ZTF23abpbuha_0,"[True, False, True, True, True, True]","[60248.48346060002, 60248.50972220022, 60251.4...","[13.62036221217015, 14.48718316429837, 11.4438...","[169.48633315872158, 32.28439269439875, 157.16...","[2, 1, 2, 1, 2, 2]"

In [46]:
df_partitions.oid.unique()

array(['ZTF18adldhip_0', 'ZTF18adldhip_1', 'ZTF18adldhip_2', ...,
       'ZTF23aboxuyi_1', 'ZTF23abpbdyh_0', 'ZTF23abpbuha_0'], dtype=object)

In [47]:
df_lc[df_lc.oid.isin(df_partitions.oid.unique())]

,oid,detected,mjd,sigma_flux_diff_ujy,flux_diff_ujy,fid
3,ZTF17aaaaabj_3,"[False, False, False, True, True, True, True, ...","[59043.470949099865, 59043.47599539999, 59043....","[4.021680458844159, 4.18601374614786, 4.365849...","[19.587287226180354, 4.68433612312114, 0.74238...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
12,ZTF17aaaaaej_5,"[True, True, True, True, True, True, True, Tru...","[59787.484143500216, 59787.48666669987, 59788....","[4.011610460702935, 3.8685977854458247, 4.1426...","[132.73786205442275, 130.65187755858432, -159....","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, ..."
14,ZTF17aaaaafz_0,"[False, True, False, True, False, False, False...","[58206.16430559987, 58231.14488429995, 58234.1...","[8.334198519710379, 9.206879583386137, 17.2728...","[20.93581016164701, 85.15186635623513, -14.291...","[1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ..."
15,ZTF17aaaaafz_1,"[True, True, True, True, True, True, True, Tru...","[58503.22148150019, 58505.11980320001, 58505.1...","[10.66184021489383, 6.68725946520036, 9.476142...","[-82.19465034260726, -301.0504183933542, -73.0...","[1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, ..."
16,ZTF17aaaaafz_2,"[True, True, True, True, True, True, True, Tru...","[58806.42609950015, 58806.4265509001, 58806.42...","[4.830327496378002, 4.950453165721698, 4.83388...","[198.88405845006156, 193.70281097080766, 190.3...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
...,...,...,...,...,...,...
253010,ZTF23abobwsd_0,"[False, False, False, False, False, False, Fal...","[60221.32445599977, 60221.36464119982, 60223.2...","[4.50945021489488, 4.5113689816309765, 4.14554...","[-6.1656230209345555, 1.9790447084421814, 3.05...","[2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, ..."
253011,ZTF23abofpay_0,"[False, False, False, False, False, False, Fal...","[60221.207939799875, 60221.24505789997, 60223....","[4.365858020242146, 5.083975012448924, 4.79596...","[-0.18967056540238775, -3.1798984307751734, -4...","[1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, ..."
253013,ZTF23aboxuyi_1,"[False, False, False, False, False, False, Tru...","[59418.46142360009, 59422.43584490009, 59426.4...","[10.31127100662421, 7.095175466434133, 4.76234...","[22.27578010361939, 27.833914276248418, 15.723...","[1, 2, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3, 2, 1, ..."
253015,ZTF23abpbdyh_0,"[False, False, False, False, False, False, Fal...","[60236.48218750022, 60238.51758099999, 60242.4...","[5.791383450140314, 3.544662523295157, 2.92826...","[6.666708298405723, 3.4420276517688113, 3.3954...","[2, 2, 1, 2, 1, 2, 1, 1, 1, 2]"
253016,ZTF23abpbuha_0,"[True, False, True, True, True, True]","[60248.48346060002, 60248.50972220022, 60251.4...","[13.62036221217015, 14.48718316429837, 11.4438...","[169.48633315872158, 32.28439269439875, 157.16...","[2, 1, 2, 1, 2, 2]"

In [65]:
from data.src.partitions import get_partitions, ordered_partitions

In [68]:
def ordered_partitions(df_lc, partitions, fold, dict_cols):
    this_partition = partitions[(partitions['partition'] == 'training_%d' %  fold) | \
                                (partitions['partition'] == 'validation_%d' % fold) | \
                                (partitions['partition'] == 'test')]
    print(this_partition)
    this_partition       = this_partition.set_index(dict_cols['oid'])
    print(this_partition)
    this_partition_final = this_partition.filter(items=df_lc.index, axis=0)
    this_partition_final['unique_id'] = np.arange(len(this_partition_final))
    this_partition_final = this_partition_final.reset_index().rename(columns={'index': dict_cols['oid']})
    this_partition_final = this_partition_final.set_index('unique_id')
    return this_partition_final

In [69]:
num_folds = 5
all_partitions = {}
for fold in range(num_folds):
    all_partitions['fold_%s' % fold] = ordered_partitions(df_lc, 
                                                          df_partitions, 
                                                          fold,
                                                          dict_cols)

                  oid alerceclass     partition
0      ZTF18adldhip_0         AGN          test
1      ZTF18adldhip_1         AGN          test
2      ZTF18adldhip_2         AGN          test
3      ZTF18adldhip_3         AGN          test
4      ZTF19aasbgeb_0         QSO          test
...               ...         ...           ...
32328  ZTF23abnzxou_2       RSCVn    training_0
32329  ZTF23abobwsd_0        SNII    training_0
32330  ZTF23aboxuyi_0         QSO  validation_0
32331  ZTF23abpbdyh_0     CV/Nova  validation_0
32332  ZTF23abpbuha_0        SNII    training_0

[86478 rows x 3 columns]
               alerceclass     partition
oid
ZTF18adldhip_0         AGN          test
ZTF18adldhip_1         AGN          test
ZTF18adldhip_2         AGN          test
ZTF18adldhip_3         AGN          test
ZTF19aasbgeb_0         QSO          test
...                    ...           ...
ZTF23abnzxou_2       RSCVn    training_0
ZTF23abobwsd_0        SNII    training_0
ZTF23aboxuyi_0         QSO  validation_0
ZTF23abpbdyh_0     CV/Nova  validation_0
ZTF23abpbuha_0        SNII    training_0

[86478 rows x 2 columns]
                  oid alerceclass     partition
0      ZTF18adldhip_0         AGN          test
1      ZTF18adldhip_1         AGN          test
2      ZTF18adldhip_2         AGN          test
3      ZTF18adldhip_3         AGN          test
4      ZTF19aasbgeb_0         QSO          test
...               ...         ...           ...
35972  ZTF17aabsapj_0         YSO  validation_1
35973  ZTF18abflrzm_5          EA  validation_1
35974  ZTF18aaywued_5       EB/EW  validation_1
35975  ZTF22aaabppe_7        SNIa  validation_1
35976  ZTF19abxnoad_0         AGN  validation_1

[86478 rows x 3 columns]
               alerceclass     partition
oid
ZTF18adldhip_0         AGN          test
ZTF18adldhip_1         AGN          test
ZTF18adldhip_2         AGN          test
ZTF18adldhip_3         AGN          test
ZTF19aasbgeb_0         QSO          test
...                    ...           ...
ZTF17aabsapj_0         YSO  validation_1
ZTF18abflrzm_5          EA  validation_1
ZTF18aaywued_5       EB/EW  validation_1
ZTF22aaabppe_7        SNIa  validation_1
ZTF19abxnoad_0         AGN  validation_1

[86478 rows x 2 columns]
                  oid alerceclass     partition
0      ZTF18adldhip_0         AGN          test
1      ZTF18adldhip_1         AGN          test
2      ZTF18adldhip_2         AGN          test
3      ZTF18adldhip_3         AGN          test
4      ZTF19aasbgeb_0         QSO          test
...               ...         ...           ...
35972  ZTF18abmiwcq_3         LPV  validation_2
35973  ZTF20abemolw_6        DSCT  validation_2
35974  ZTF18aaaarmd_3         LPV  validation_2
35975  ZTF21acqojzp_1     CV/Nova  validation_2
35976  ZTF21aaldtxq_1        DSCT  validation_2

[86478 rows x 3 columns]
               alerceclass     partition
oid
ZTF18adldhip_0         AGN          test
ZTF18adldhip_1         AGN          test
ZTF18adldhip_2         AGN          test
ZTF18adldhip_3         AGN          test
ZTF19aasbgeb_0         QSO          test
...                    ...           ...
ZTF18abmiwcq_3         LPV  validation_2
ZTF20abemolw_6        DSCT  validation_2
ZTF18aaaarmd_3         LPV  validation_2
ZTF21acqojzp_1     CV/Nova  validation_2
ZTF21aaldtxq_1        DSCT  validation_2

[86478 rows x 2 columns]
                  oid     alerceclass     partition
0      ZTF18adldhip_0             AGN          test
1      ZTF18adldhip_1             AGN          test
2      ZTF18adldhip_2             AGN          test
3      ZTF18adldhip_3             AGN          test
4      ZTF19aasbgeb_0             QSO          test
...               ...             ...           ...
35972  ZTF20adcchxz_0           EB/EW  validation_3
35973  ZTF19aayhsje_2  Periodic-Other  validation_3
35974  ZTF18aavqmck_3              EA  validation_3
35975  ZTF21aayrytd_2             CEP  validation_3
35976  ZTF18acdwayr_1             QSO  validation_3

[86478 rows x 3 columns]
                   alerceclass     partition
oid
ZTF18adldhip_0             AGN          test
ZTF18adldhip_1             AGN          test
ZTF18adldhip_2             AGN          test
ZTF18adldhip_3             AGN          test
ZTF19aasbgeb_0             QSO          test
...                        ...           ...
ZTF20adcchxz_0           EB/EW  validation_3
ZTF19aayhsje_2  Periodic-Other  validation_3
ZTF18aavqmck_3              EA  validation_3
ZTF21aayrytd_2             CEP  validation_3
ZTF18acdwayr_1             QSO  validation_3

[86478 rows x 2 columns]
                  oid     alerceclass     partition
0      ZTF18adldhip_0             AGN          test
1      ZTF18adldhip_1             AGN          test
2      ZTF18adldhip_2             AGN          test
3      ZTF18adldhip_3             AGN          test
4      ZTF19aasbgeb_0             QSO          test
...               ...             ...           ...
35972  ZTF19acokmuo_7             AGN  validation_4
35973  ZTF18abxoxih_1          Blazar  validation_4
35974  ZTF18adbhpsf_1          Blazar  validation_4
35975  ZTF21aamkwra_0  Periodic-Other  validation_4
35976  ZTF23aaqniyk_0            SNII  validation_4

[86478 rows x 3 columns]
                   alerceclass     partition
oid
ZTF18adldhip_0             AGN          test
ZTF18adldhip_1             AGN          test
ZTF18adldhip_2             AGN          test
ZTF18adldhip_3             AGN          test
ZTF19aasbgeb_0             QSO          test
...                        ...           ...
ZTF19acokmuo_7             AGN  validation_4
ZTF18abxoxih_1          Blazar  validation_4
ZTF18adbhpsf_1          Blazar  validation_4
ZTF21aamkwra_0  Periodic-Other  validation_4
ZTF23aaqniyk_0            SNII  validation_4

[86478 rows x 2 columns]

In [67]:
all_partitions

{'fold_0': Empty DataFrame
 Columns: [oid, alerceclass, partition]
 Index: [],
 'fold_1': Empty DataFrame
 Columns: [oid, alerceclass, partition]
 Index: [],
 'fold_2': Empty DataFrame
 Columns: [oid, alerceclass, partition]
 Index: [],
 'fold_3': Empty DataFrame
 Columns: [oid, alerceclass, partition]
 Index: [],
 'fold_4': Empty DataFrame
 Columns: [oid, alerceclass, partition]
 Index: []}

In [17]:
partitions_final[2].sort_values(by='oid').oid.nunique()

33382

In [18]:
partitions_final[3].sort_values(by='oid').oid.nunique()

33382

In [19]:
partitions_final[1].sort_values(by='oid')

                oid  window_id alerceclass     partition
0      ZTF17aaaaabj          3        RRLc    training_0
1      ZTF17aaaaaej          5        RRLc  validation_0
2      ZTF17aaaaajg          1        RRLc    training_0
3      ZTF17aaaaavq          4         LPV  validation_0
4      ZTF17aaaaaya          6       RRLab    training_0
...             ...        ...         ...           ...
32329  ZTF23abobwsd          0        SNII    training_0
6445   ZTF23abofpay          0       SNIbc    training_0
32330  ZTF23aboxuyi          1         QSO  validation_0
32331  ZTF23abpbdyh          0     CV/Nova  validation_0
32332  ZTF23abpbuha          0        SNII    training_0

[35977 rows x 4 columns]

In [20]:
partitions_final[2].sort_values(by='oid')

                oid  window_id alerceclass     partition
2117   ZTF17aaaaabj          3        RRLc    training_1
18375  ZTF17aaaaaej          5        RRLc    training_1
2758   ZTF17aaaaajg          1        RRLc    training_1
12336  ZTF17aaaaavq          4         LPV    training_1
24433  ZTF17aaaaaya          6       RRLab    training_1
...             ...        ...         ...           ...
31187  ZTF23abobwsd          0        SNII  validation_1
1125   ZTF23abofpay          0       SNIbc    training_1
21240  ZTF23aboxuyi          1         QSO    training_1
18230  ZTF23abpbdyh          0     CV/Nova    training_1
31257  ZTF23abpbuha          0        SNII  validation_1

[35977 rows x 4 columns]

In [21]:
partitions_final[2].groupby('alerceclass').count().sort_values(by='oid')

                 oid  window_id  partition
alerceclass
Microlensing     125        125        125
SNIIb            317        317        317
TDE              345        345        345
SLSN             490        490        490
SNIIn            855        855        855
Periodic-Other  1067       1067       1067
Blazar          1182       1182       1182
SNII            1289       1289       1289
DSCT            1326       1326       1326
CV/Nova         1427       1427       1427
SNIbc           1512       1512       1512
RSCVn           2062       2062       2062
SNIa            2393       2393       2393
AGN             2395       2395       2395
CEP             2396       2396       2396
YSO             2397       2397       2397
QSO             2398       2398       2398
RRLab           2399       2399       2399
EB/EW           2400       2400       2400
EA              2400       2400       2400
RRLc            2400       2400       2400
LPV             2402       2402       2402

In [22]:
partitions_final[2].groupby('alerceclass').count().sort_values(by='oid')

                 oid  window_id  partition
alerceclass
Microlensing     125        125        125
SNIIb            317        317        317
TDE              345        345        345
SLSN             490        490        490
SNIIn            855        855        855
Periodic-Other  1067       1067       1067
Blazar          1182       1182       1182
SNII            1289       1289       1289
DSCT            1326       1326       1326
CV/Nova         1427       1427       1427
SNIbc           1512       1512       1512
RSCVn           2062       2062       2062
SNIa            2393       2393       2393
AGN             2395       2395       2395
CEP             2396       2396       2396
YSO             2397       2397       2397
QSO             2398       2398       2398
RRLab           2399       2399       2399
EB/EW           2400       2400       2400
EA              2400       2400       2400
RRLc            2400       2400       2400
LPV             2402       2402       2402

In [25]:
df_aux = pd.concat([partitions_final[0], partitions_final[1]])
df_aux

                oid  window_id alerceclass     partition
0      ZTF18adldhip          0         AGN          test
1      ZTF18adldhip          1         AGN          test
2      ZTF18adldhip          2         AGN          test
3      ZTF18adldhip          3         AGN          test
4      ZTF19aasbgeb          0         QSO          test
...             ...        ...         ...           ...
32328  ZTF23abnzxou          1       RSCVn    training_0
32329  ZTF23abobwsd          0        SNII    training_0
32330  ZTF23aboxuyi          1         QSO  validation_0
32331  ZTF23abpbdyh          0     CV/Nova  validation_0
32332  ZTF23abpbuha          0        SNII    training_0

[86478 rows x 4 columns]

In [23]:
df_lc

,oid,window_id,detected,mjd,sigma_flux_diff_ujy,flux_diff_ujy,fid
0,ZTF17aaaaabj,0,"[True, True, True, False, True, True, True, Tr...","[58206.16430559987, 58231.14488429995, 58234.1...","[8.440242655407886, 9.70802999032586, 20.01827...","[-249.57181969652103, 52.815739767359396, -253...","[1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, ..."
1,ZTF17aaaaabj,1,"[True, True, True, True, True, True, True, Tru...","[58491.22325230017, 58493.221169000026, 58493....","[4.335927383739846, 2.337136437970241, 2.61231...","[318.88202860232195, -230.68964424237782, -148...","[2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, ..."
2,ZTF17aaaaabj,2,"[True, True, True, True, True, True, True, Tru...","[58806.42067130003, 58806.421134300064, 58806....","[3.3180606229102576, 3.4208377390652815, 3.416...","[-343.69137256798797, -341.49161921565184, -35...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
3,ZTF17aaaaabj,3,"[False, False, False, True, True, True, True, ...","[59043.470949099865, 59043.47599539999, 59043....","[4.021680458844159, 4.18601374614786, 4.365849...","[19.587287226180354, 4.68433612312114, 0.74238...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
4,ZTF17aaaaabj,4,"[True, True, True, True, True, True, True, Tru...","[59294.158067100216, 59294.19618060021, 59296....","[7.990314418768771, 8.825867966180457, 10.4053...","[196.79623824291224, 301.52910950582645, -288....","[1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ..."
...,...,...,...,...,...,...,...
253012,ZTF23aboxuyi,0,"[False, False, False, False, False, False, Fal...","[58872.165138899814, 58875.09256940009, 58875....","[4.789168652528449, 6.6113980531103085, 4.0210...","[1.1547001816474889, -0.84922994538376, 0.5157...","[1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, ..."
253013,ZTF23aboxuyi,1,"[False, False, False, False, False, False, Tru...","[59418.46142360009, 59422.43584490009, 59426.4...","[10.31127100662421, 7.095175466434133, 4.76234...","[22.27578010361939, 27.833914276248418, 15.723...","[1, 2, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3, 2, 1, ..."
253014,ZTF23aboxuyi,2,"[False, False, False, False, False, False, Fal...","[59803.41695600003, 59803.45730319992, 59808.4...","[8.438503543741724, 9.441484804282839, 5.70083...","[13.20777222894057, 17.15569121649437, 12.1412...","[2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, ..."
253015,ZTF23abpbdyh,0,"[False, False, False, False, False, False, Fal...","[60236.48218750022, 60238.51758099999, 60242.4...","[5.791383450140314, 3.544662523295157, 2.92826...","[6.666708298405723, 3.4420276517688113, 3.3954...","[2, 2, 1, 2, 1, 2, 1, 1, 1, 2]"
253016,ZTF23abpbuha,0,"[True, False, True, True, True, True]","[60248.48346060002, 60248.50972220022, 60251.4...","[13.62036221217015, 14.48718316429837, 11.4438...","[169.48633315872158, 32.28439269439875, 157.16...","[2, 1, 2, 1, 2, 2]"