In [85]:
import glob
import pickle

In [86]:
aos_paths = glob.glob('/home/mdelafuente/batch_processing/aos/*')#[3:]
with open(f'{aos_paths[0]}', 'rb') as f:
    data = pickle.load(f)

# Now, 'data' contains the loaded object
print(data.features)

Empty DataFrame
Columns: [name, value, fid, sid, version]
Index: []

In [87]:

ZTF_ff_columns_to_PROD= {
    "g-r_mean_g,r": "g_r_mean_12",
    "g-r_max_g,r": "g_r_max_12",
    "g-r_mean_corr_g,r": "g_r_mean_corr_12",
    "g-r_max_corr_g,r": "g_r_max_corr_12",
    "W1-W2": "W1_W2",
    "W2-W3": "W2_W3",
    "W3-W4": "W3_W4",
    "g-W1": "g_W1",
    "r-W1": "r_W1",
    "g-W2": "g_W2",
    "r-W2": "r_W2",
    "g-W3": "g_W3",
    "r-W3": "r_W3",
    "g-W4": "g_W4",
    "r-W4": "r_W4",
    "MHPS_ratio_g": "MHPS_ratio_1",
    "MHPS_low_g": "MHPS_low_1",
    "MHPS_high_g": "MHPS_high_1",
    "MHPS_non_zero_g": "MHPS_non_zero_1",
    "MHPS_PN_flag_g": "MHPS_PN_flag_1",
    "MHPS_ratio_r": "MHPS_ratio_2",
    "MHPS_low_r": "MHPS_low_2",
    "MHPS_high_r": "MHPS_high_2",
    "MHPS_non_zero_r": "MHPS_non_zero_2",
    "MHPS_PN_flag_r": "MHPS_PN_flag_2",
    "GP_DRW_sigma_g": "GP_DRW_sigma_1",
    "GP_DRW_tau_g": "GP_DRW_tau_1",
    "GP_DRW_sigma_r": "GP_DRW_sigma_2",
    "GP_DRW_tau_r": "GP_DRW_tau_2",
    "Multiband_period_g,r": "Multiband_period_12",
    "PPE_g,r": "PPE_12",
    "Period_band_g": "Period_band_1",
    "delta_period_g": "delta_period_1",
    "Period_band_r": "Period_band_2",
    "delta_period_r": "delta_period_2",
    "Power_rate_1_4_g,r": "Power_rate_1_4_12",
    "Power_rate_1_3_g,r": "Power_rate_1_3_12",
    "Power_rate_1_2_g,r": "Power_rate_1_2_12",
    "Power_rate_2_g,r": "Power_rate_2_12",
    "Power_rate_3_g,r": "Power_rate_3_12",
    "Power_rate_4_g,r": "Power_rate_4_12",
    "Psi_CS_g": "Psi_CS_1",
    "Psi_eta_g": "Psi_eta_1",
    "Psi_CS_r": "Psi_CS_2",
    "Psi_eta_r": "Psi_eta_2",
    "Amplitude_g": "Amplitude_1",
    "AndersonDarling_g": "AndersonDarling_1",
    "Autocor_length_g": "Autocor_length_1",
    "Beyond1Std_g": "Beyond1Std_1",
    "Con_g": "Con_1",
    "Eta_e_g": "Eta_e_1",
    "Gskew_g": "Gskew_1",
    "MaxSlope_g": "MaxSlope_1",
    "Mean_g": "Mean_1",
    "Meanvariance_g": "Meanvariance_1",
    "MedianAbsDev_g": "MedianAbsDev_1",
    "MedianBRP_g": "MedianBRP_1",
    "PairSlopeTrend_g": "PairSlopeTrend_1",
    "PercentAmplitude_g": "PercentAmplitude_1",
    "Q31_g": "Q31_1",
    "Rcs_g": "Rcs_1",
    "Skew_g": "Skew_1",
    "SmallKurtosis_g": "SmallKurtosis_1",
    "Std_g": "Std_1",
    "StetsonK_g": "StetsonK_1",
    "Pvar_g": "Pvar_1",
    "ExcessVar_g": "ExcessVar_1",
    "SF_ML_amplitude_g": "SF_ML_amplitude_1",
    "SF_ML_gamma_g": "SF_ML_gamma_1",
    "IAR_phi_g": "IAR_phi_1",
    "LinearTrend_g": "LinearTrend_1",
    "Amplitude_r": "Amplitude_2",
    "AndersonDarling_r": "AndersonDarling_2",
    "Autocor_length_r": "Autocor_length_2",
    "Beyond1Std_r": "Beyond1Std_2",
    "Con_r": "Con_2",
    "Eta_e_r": "Eta_e_2",
    "Gskew_r": "Gskew_2",
    "MaxSlope_r": "MaxSlope_2",
    "Mean_r": "Mean_2",
    "Meanvariance_r": "Meanvariance_2",
    "MedianAbsDev_r": "MedianAbsDev_2",
    "MedianBRP_r": "MedianBRP_2",
    "PairSlopeTrend_r": "PairSlopeTrend_2",
    "PercentAmplitude_r": "PercentAmplitude_2",
    "Q31_r": "Q31_2",
    "Rcs_r": "Rcs_2",
    "Skew_r": "Skew_2",
    "SmallKurtosis_r": "SmallKurtosis_2",
    "Std_r": "Std_2",
    "StetsonK_r": "StetsonK_2",
    "Pvar_r": "Pvar_2",
    "ExcessVar_r": "ExcessVar_2",
    "SF_ML_amplitude_r": "SF_ML_amplitude_2",
    "SF_ML_gamma_r": "SF_ML_gamma_2",
    "IAR_phi_r": "IAR_phi_2",
    "LinearTrend_r": "LinearTrend_2",
    "sgscore1": "sgscore1",
    "dist_nr": "dist_nr",
    "ps_g-r": "ps_g_r",
    "SPM_A_g": "SPM_A_1",
    "SPM_t0_g": "SPM_t0_1",
    "SPM_gamma_g": "SPM_gamma_1",
    "SPM_beta_g": "SPM_beta_1",
    "SPM_tau_rise_g": "SPM_tau_rise_1",
    "SPM_tau_fall_g": "SPM_tau_fall_1",
    "SPM_A_r": "SPM_A_2",
    "SPM_t0_r": "SPM_t0_2",
    "SPM_gamma_r": "SPM_gamma_2",
    "SPM_beta_r": "SPM_beta_2",
    "SPM_tau_rise_r": "SPM_tau_rise_2",
    "SPM_tau_fall_r": "SPM_tau_fall_2",
    "SPM_chi_g": "SPM_chi_1",
    "SPM_chi_r": "SPM_chi_2",
    "TDE_decay_g": "TDE_decay_1",
    "TDE_decay_chi_g": "TDE_decay_chi_1",
    "TDE_decay_r": "TDE_decay_2",
    "TDE_decay_chi_r": "TDE_decay_chi_2",
    "fleet_a_g": "fleet_a_1",
    "fleet_w_g": "fleet_w_1",
    "fleet_chi_g": "fleet_chi_1",
    "fleet_a_r": "fleet_a_2",
    "fleet_w_r": "fleet_w_2",
    "fleet_chi_r": "fleet_chi_2",
    "color_variation_g,r": "color_variation_12",
    "positive_fraction_g": "positive_fraction_1",
    "n_forced_phot_band_before_g": "n_forced_phot_band_before_1",
    "dbrightness_first_det_band_g": "dbrightness_first_det_band_1",
    "dbrightness_forced_phot_band_g": "dbrightness_forced_phot_band_1",
    "last_brightness_before_band_g": "last_brightness_before_band_1",
    "max_brightness_before_band_g": "max_brightness_before_band_1",
    "median_brightness_before_band_g": "median_brightness_before_band_1",
    "n_forced_phot_band_after_g": "n_forced_phot_band_after_1",
    "max_brightness_after_band_g": "max_brightness_after_band_1",
    "median_brightness_after_band_g": "median_brightness_after_band_1",
    "positive_fraction_r": "positive_fraction_2",
    "n_forced_phot_band_before_r": "n_forced_phot_band_before_2",
    "dbrightness_first_det_band_r": "dbrightness_first_det_band_2",
    "dbrightness_forced_phot_band_r": "dbrightness_forced_phot_band_2",
    "last_brightness_before_band_r": "last_brightness_before_band_2",
    "max_brightness_before_band_r": "max_brightness_before_band_2",
    "median_brightness_before_band_r": "median_brightness_before_band_2",
    "n_forced_phot_band_after_r": "n_forced_phot_band_after_2",
    "max_brightness_after_band_r": "max_brightness_after_band_2",
    "median_brightness_after_band_r": "median_brightness_after_band_2",
    "ulens_u0_g": "ulens_u0_1",
    "ulens_tE_g": "ulens_tE_1",
    "ulens_fs_g": "ulens_fs_1",
    "ulens_chi_g": "ulens_chi_1",
    "ulens_u0_r": "ulens_u0_2",
    "ulens_tE_r": "ulens_tE_2",
    "ulens_fs_r": "ulens_fs_2",
    "ulens_chi_r": "ulens_chi_2",
    "Harmonics_mse_g": "Harmonics_mse_1",
    "Harmonics_chi_g": "Harmonics_chi_1",
    "Harmonics_mag_1_g": "Harmonics_mag_1_1",
    "Harmonics_mag_2_g": "Harmonics_mag_2_1",
    "Harmonics_phase_2_g": "Harmonics_phase_2_1",
    "Harmonics_mag_3_g": "Harmonics_mag_3_1",
    "Harmonics_phase_3_g": "Harmonics_phase_3_1",
    "Harmonics_mag_4_g": "Harmonics_mag_4_1",
    "Harmonics_phase_4_g": "Harmonics_phase_4_1",
    "Harmonics_mag_5_g": "Harmonics_mag_5_1",
    "Harmonics_phase_5_g": "Harmonics_phase_5_1",
    "Harmonics_mag_6_g": "Harmonics_mag_6_1",
    "Harmonics_phase_6_g": "Harmonics_phase_6_1",
    "Harmonics_mag_7_g": "Harmonics_mag_7_1",
    "Harmonics_phase_7_g": "Harmonics_phase_7_1",
    "Harmonics_mse_r": "Harmonics_mse_2",
    "Harmonics_chi_r": "Harmonics_chi_2",
    "Harmonics_mag_1_r": "Harmonics_mag_1_2",
    "Harmonics_mag_2_r": "Harmonics_mag_2_2",
    "Harmonics_phase_2_r": "Harmonics_phase_2_2",
    "Harmonics_mag_3_r": "Harmonics_mag_3_2",
    "Harmonics_phase_3_r": "Harmonics_phase_3_2",
    "Harmonics_mag_4_r": "Harmonics_mag_4_2",
    "Harmonics_phase_4_r": "Harmonics_phase_4_2",
    "Harmonics_mag_5_r": "Harmonics_mag_5_2",
    "Harmonics_phase_5_r": "Harmonics_phase_5_2",
    "Harmonics_mag_6_r": "Harmonics_mag_6_2",
    "Harmonics_phase_6_r": "Harmonics_phase_6_2",
    "Harmonics_mag_7_r": "Harmonics_mag_7_2",
    "Harmonics_phase_7_r": "Harmonics_phase_7_2",
    "Timespan": "Timespan",
    "Coordinate_x": "Coordinate_x",
    "Coordinate_y": "Coordinate_y",
    "Coordinate_z": "Coordinate_z",
}

In [88]:
astro_object = data

In [89]:
import yaml
with open("/home/mdelafuente/batch_processing/pipeline/training/lc_classifier_ztf/ATAT_ALeRCE/data/datasets/ZTF_ff/final/LC_MD_FEAT_240627_windows_200_12/dict_info.yaml", 'r') as stream:
    
    config = yaml.safe_load(stream)

In [90]:
from pipeline.lc_classifier.lc_classifier.features.composites.ztf import ZTFFeatureExtractor
ex = ZTFFeatureExtractor()
ex.compute_features_batch([astro_object])

/home/mdelafuente/batch_processing/pipeline/lc_classifier/lc_classifier/features/extractors/tde_extractor.py:173: OptimizeWarning: Covariance of the parameters could not be estimated
  parameters, _ = curve_fit(
/home/mdelafuente/batch_processing/pipeline/lc_classifier/lc_classifier/features/extractors/ulens_extractor.py:80: OptimizeWarning: Covariance of the parameters could not be estimated
  parameters, _ = curve_fit(

In [91]:
astro_object.features

             name                  value   fid  sid version
0        g-r_mean               1.475964   g,r  ZTF   1.0.0
1         g-r_max               0.519332   g,r  ZTF   1.0.0
2   g-r_mean_corr               0.581621   g,r  ZTF   1.0.0
3    g-r_max_corr               0.333409   g,r  ZTF   1.0.0
0           W1-W2  -0.017999999999998906  None  ZTF   1.0.0
..            ...                    ...   ...  ...     ...
11    ulens_mag_0              12.739505     r  ZTF   1.0.1
0        Timespan            1457.009794  None  ZTF   1.0.0
0    Coordinate_x              -0.421299  None  ZTF   1.0.0
1    Coordinate_y               0.551256  None  ZTF   1.0.0
2    Coordinate_z               0.720156  None  ZTF   1.0.0

[197 rows x 5 columns]

In [92]:

astro_object.features['fid']= astro_object.features['fid'].fillna('')

In [93]:
astro_object.features["name_fid"] = astro_object.features.apply(
    lambda row: f"{row['name']}_{row['fid']}" if row['fid'] != '' else row['name'], axis=1 
)

In [94]:
astro_object.features

             name                  value  fid  sid version           name_fid
0        g-r_mean               1.475964  g,r  ZTF   1.0.0       g-r_mean_g,r
1         g-r_max               0.519332  g,r  ZTF   1.0.0        g-r_max_g,r
2   g-r_mean_corr               0.581621  g,r  ZTF   1.0.0  g-r_mean_corr_g,r
3    g-r_max_corr               0.333409  g,r  ZTF   1.0.0   g-r_max_corr_g,r
0           W1-W2  -0.017999999999998906       ZTF   1.0.0              W1-W2
..            ...                    ...  ...  ...     ...                ...
11    ulens_mag_0              12.739505    r  ZTF   1.0.1      ulens_mag_0_r
0        Timespan            1457.009794       ZTF   1.0.0           Timespan
0    Coordinate_x              -0.421299       ZTF   1.0.0       Coordinate_x
1    Coordinate_y               0.551256       ZTF   1.0.0       Coordinate_y
2    Coordinate_z               0.720156       ZTF   1.0.0       Coordinate_z

[197 rows x 6 columns]

In [95]:
astro_object.features['prod']  = astro_object.features['name_fid'].map(ZTF_ff_columns_to_PROD)

In [96]:
astro_object.features = astro_object.features.dropna(subset = 'prod')

In [97]:
astro_object.features

,name,value,fid,sid,version,name_fid,prod
0,g-r_mean,1.475964,"g,r",ZTF,1.0.0,"g-r_mean_g,r",g_r_mean_12
1,g-r_max,0.519332,"g,r",ZTF,1.0.0,"g-r_max_g,r",g_r_max_12
2,g-r_mean_corr,0.581621,"g,r",ZTF,1.0.0,"g-r_mean_corr_g,r",g_r_mean_corr_12
3,g-r_max_corr,0.333409,"g,r",ZTF,1.0.0,"g-r_max_corr_g,r",g_r_max_corr_12
0,W1-W2,-0.017999999999998906,,ZTF,1.0.0,W1-W2,W1_W2
...,...,...,...,...,...,...,...
9,ulens_chi,NaN,r,ZTF,1.0.1,ulens_chi_r,ulens_chi_2
0,Timespan,1457.009794,,ZTF,1.0.0,Timespan,Timespan
0,Coordinate_x,-0.421299,,ZTF,1.0.0,Coordinate_x,Coordinate_x
1,Coordinate_y,0.551256,,ZTF,1.0.0,Coordinate_y,Coordinate_y
2,Coordinate_z,0.720156,,ZTF,1.0.0,Coordinate_z,Coordinate_z

In [98]:
features =  astro_object.features[~astro_object.features['prod'].isin(config["md_cols"])]
metadata =  astro_object.features[astro_object.features['prod'].isin(config["md_cols"])]

In [99]:
features

,name,value,fid,sid,version,name_fid,prod
0,g-r_mean,1.475964,"g,r",ZTF,1.0.0,"g-r_mean_g,r",g_r_mean_12
1,g-r_max,0.519332,"g,r",ZTF,1.0.0,"g-r_max_g,r",g_r_max_12
2,g-r_mean_corr,0.581621,"g,r",ZTF,1.0.0,"g-r_mean_corr_g,r",g_r_mean_corr_12
3,g-r_max_corr,0.333409,"g,r",ZTF,1.0.0,"g-r_max_corr_g,r",g_r_max_corr_12
3,g-W1,1.410343750000001,,ZTF,1.0.0,g-W1,g_W1
...,...,...,...,...,...,...,...
9,ulens_chi,NaN,r,ZTF,1.0.1,ulens_chi_r,ulens_chi_2
0,Timespan,1457.009794,,ZTF,1.0.0,Timespan,Timespan
0,Coordinate_x,-0.421299,,ZTF,1.0.0,Coordinate_x,Coordinate_x
1,Coordinate_y,0.551256,,ZTF,1.0.0,Coordinate_y,Coordinate_y
2,Coordinate_z,0.720156,,ZTF,1.0.0,Coordinate_z,Coordinate_z

In [100]:
metadata

       name                  value fid        sid version  name_fid      prod
0     W1-W2  -0.017999999999998906            ZTF   1.0.0     W1-W2     W1_W2
1     W2-W3   0.006000000000000227            ZTF   1.0.0     W2-W3     W2_W3
2     W3-W4                  2.901            ZTF   1.0.0     W3-W4     W3_W4
0  sgscore1                    1.0      panstarrs   1.0.0  sgscore1  sgscore1
1   dist_nr               0.111956      panstarrs   1.0.0   dist_nr   dist_nr
2    ps_g-r                  0.261      panstarrs   1.0.0    ps_g-r    ps_g_r

In [101]:
feat_cols = features['value']

In [102]:
feat_cols.fillna(-1).values

array([1.4759638249999991, 0.5193320000000003, 0.5816207500000008,
       0.3334089999999996, '1.410343750000001', '0.8287230000000001',
       '1.392343750000002', '0.8107230000000012', '1.3983437500000022',
       '0.8167230000000014', '4.299343750000002', '3.717723000000001', -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, 11343819.092804909, 1.0, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       51.818781918634656, 476.89428136705897, 120.0, 0.0, 100.0, 180.0,
       10.157931254711379, 97.39843105531679, 1.0, 0.019912270671675947,
       100.0, 180.0, -1, -1, 2.5986947462941488, -1, 0.4968170198345776,
       0.06077598178894438, -1, -1, -1, 1.774220756684118,
       -0.005001883531838374, -1, -1, 0.6, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, 1.0, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0.6159491865798182,
       5.6886596011773545, 0.49994882819340036, -1, 0.8846274346568755,
       26.032993666116518, 0.529994382837186, -1, 1457.0097936945967,
       -0.4212989151532868, 0.5512558496604028, 0.7201556861581051],
      dtype=object)

In [103]:
md_cols = metadata['value']

In [104]:
md_cols.fillna(-1).values

array(['-0.017999999999998906', '0.006000000000000227', '2.901', 1.0,
       0.11195635, 0.26099999999999923], dtype=object)

In [120]:
ao_dict = astro_object.to_dict()

In [121]:
ao_dict['ft_cols'] = feat_cols
ao_dict['md_cols'] = md_cols

In [122]:
ao_dict

{'metadata':         name             value
 0        aid  aid_ZTF18aacjwwd
 1        oid      ZTF18aacjwwd
 2         W1            11.848
 3         W2            11.866
 4         W3             11.86
 5         W4             8.959
 6   sgscore1               1.0
 7     sgmag1            13.373
 8     srmag1            13.112
 9  distpsnr1          0.111956,
 'detections':                            oid               candid            pid  \
 aid
 aid_ZTF18aacjwwd  ZTF18aacjwwd   686455332615015070   686455332615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   701535122615015170   701535122615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   758431092615015038   758431092615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   758431092615015039   758431092615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   808153742615015248   808153742615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   988513582615010082   988513582615
 aid_ZTF18aacjwwd  ZTF18aacjwwd  1109181522615010010  1109181522615
 aid_ZTF18aacjwwd  ZTF18aacjwwd  1721473052615015103  1721473052615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   686455332615015070   686455332615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   701535122615015170   701535122615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   758431092615015038   758431092615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   758431092615015039   758431092615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   808153742615015248   808153742615
 aid_ZTF18aacjwwd  ZTF18aacjwwd   988513582615010082   988513582615
 aid_ZTF18aacjwwd  ZTF18aacjwwd  1109181522615010010  1109181522615
 aid_ZTF18aacjwwd  ZTF18aacjwwd  1721473052615015103  1721473052615
 aid_ZTF18aacjwwd  ZTF18aacjwwd  2143467122615015010  2143467122615

                           ra        dec           mjd   brightness  \
 aid
 aid_ZTF18aacjwwd  127.389053  46.067255  58440.469873    13.178264
 aid_ZTF18aacjwwd  127.389048  46.067324  58455.556258    12.617193
 aid_ZTF18aacjwwd  127.389026  46.067318  58512.461384    12.680013
 aid_ZTF18aacjwwd  127.389043  46.067322  58512.461384    12.676603
 aid_ZTF18aacjwwd  127.389093  46.067329  58562.168992    12.733083
 aid_ZTF18aacjwwd  127.388962  46.067320  58742.495939    13.544637
 aid_ZTF18aacjwwd  127.389041  46.067362  58863.212303    13.359872
 aid_ZTF18aacjwwd  127.388839  46.067384  59475.456490    12.950602
 aid_ZTF18aacjwwd  127.389053  46.067255  58440.469873   646.757688
 aid_ZTF18aacjwwd  127.389048  46.067324  58455.556258  8360.264158
 aid_ZTF18aacjwwd  127.389026  46.067318  58512.461384  6528.000816
 aid_ZTF18aacjwwd  127.389043  46.067322  58512.461384  6624.733315
 aid_ZTF18aacjwwd  127.389093  46.067329  58562.168992  5060.581226
 aid_ZTF18aacjwwd  127.388962  46.067320  58742.495939 -4920.970936
 aid_ZTF18aacjwwd  127.389041  46.067362  58863.212303 -2347.502157
 aid_ZTF18aacjwwd  127.388839  46.067384  59475.456490  5181.878192
 aid_ZTF18aacjwwd  127.388421  46.067478  59897.479666   345.261378

                   e_brightness fid  isdiffpos  forced  tid  sid       unit
 aid
 aid_ZTF18aacjwwd      0.004869   g          1   False  ZTF  ZTF  magnitude
 aid_ZTF18aacjwwd      0.007560   r          1   False  ZTF  ZTF  magnitude
 aid_ZTF18aacjwwd      0.004737   r          1   False  ZTF  ZTF  magnitude
 aid_ZTF18aacjwwd      0.009906   r          1   False  ZTF  ZTF  magnitude
 aid_ZTF18aacjwwd      0.006518   r          1   False  ZTF  ZTF  magnitude
 aid_ZTF18aacjwwd      0.008399   g         -1   False  ZTF  ZTF  magnitude
 aid_ZTF18aacjwwd      0.008826   g         -1   False  ZTF  ZTF  magnitude
 aid_ZTF18aacjwwd      0.008292   g          1   False  ZTF  ZTF  magnitude
 aid_ZTF18aacjwwd     87.180905   g          1   False  ZTF  ZTF  diff_flux
 aid_ZTF18aacjwwd    226.955816   r          1   False  ZTF  ZTF  diff_flux
 aid_ZTF18aacjwwd    134.213915   r          1   False  ZTF  ZTF  diff_flux
 aid_ZTF18aacjwwd    281.540679   r          1   False  ZTF  ZTF  diff_flux
 aid_ZTF18aacjwwd    175.857858   r          1   False  ZTF  ZTF  diff_flux
 aid_ZTF18aacjwwd    107.312432   g         -1   False  ZTF  ZTF  diff_flux
 aid_ZTF18aacjwwd    133.690903   g         -1   False  ZTF  ZTF  diff_flux
 aid_ZTF18aacjwwd    183.092775   g          1   False  ZTF  ZTF  diff_flux
 aid_ZTF18aacjwwd     64.721760   g          1   False  ZTF  ZTF  diff_flux  ,
 'non_detections': None,
 'forced_photometry': Empty DataFrame
 Columns: [oid, candid, pid, ra, dec, mjd, brightness, e_brightness, fid, isdiffpos, forced, tid, sid, unit]
 Index: [],
 'xmatch': oid          ZTF18aacjwwd
 w1mpro             11.848
 w2mpro             11.866
 w3mpro              11.86
 w4mpro              8.959
 sgscore1              1.0
 sgmag1             13.373
 srmag1             13.112
 distpsnr1        0.111956
 Name: 329, dtype: object,
 'stamps': None,
 'features':              name                  value  fid  sid version           name_fid  \
 0        g-r_mean               1.475964  g,r  ZTF   1.0.0       g-r_mean_g,r
 1         g-r_max               0.519332  g,r  ZTF   1.0.0        g-r_max_g,r
 2   g-r_mean_corr               0.581621  g,r  ZTF   1.0.0  g-r_mean_corr_g,r
 3    g-r_max_corr               0.333409  g,r  ZTF   1.0.0   g-r_max_corr_g,r
 0           W1-W2  -0.017999999999998906       ZTF   1.0.0              W1-W2
 ..            ...                    ...  ...  ...     ...                ...
 9       ulens_chi                    NaN    r  ZTF   1.0.1        ulens_chi_r
 0        Timespan            1457.009794       ZTF   1.0.0           Timespan
 0    Coordinate_x              -0.421299       ZTF   1.0.0       Coordinate_x
 1    Coordinate_y               0.551256       ZTF   1.0.0       Coordinate_y
 2    Coordinate_z               0.720156       ZTF   1.0.0       Coordinate_z

                 prod
 0        g_r_mean_12
 1         g_r_max_12
 2   g_r_mean_corr_12
 3    g_r_max_corr_12
 0              W1_W2
 ..               ...
 9        ulens_chi_2
 0           Timespan
 0       Coordinate_x
 1       Coordinate_y
 2       Coordinate_z

 [187 rows x 7 columns],
 'predictions': Empty DataFrame
 Columns: [name, value, fid, sid, version]
 Index: [],
 'ft_cols': 0             1.475964
 1             0.519332
 2             0.581621
 3             0.333409
 3    1.410343750000001
            ...
 9                  NaN
 0          1457.009794
 0            -0.421299
 1             0.551256
 2             0.720156
 Name: value, Length: 181, dtype: object,
 'md_cols': 0    -0.017999999999998906
 1     0.006000000000000227
 2                    2.901
 0                      1.0
 1                 0.111956
 2                    0.261
 Name: value, dtype: object}